from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def read(path):
    return (ROOT / path).read_text(encoding="utf-8")


def write(path, text):
    (ROOT / path).write_text(text, encoding="utf-8", newline="\n")


def rep(path, old, new, count=1):
    text = read(path)
    actual = text.count(old)
    if actual != count:
        raise SystemExit(f"{path}: expected {count} matches, found {actual}: {old[:140]!r}")
    write(path, text.replace(old, new, count))


# 1) Quick Setup raw-axis capture: keep the stored candidate deliberately
# uncalibrated (min=max=rest), but give the transient release guard a usable
# full raw range. Otherwise InputBinding::read() returns zero immediately and
# Quick Setup can start the next step while the wheel/pedal is still displaced.
anchor = '''\t//\n\t// Listens for any input at all rather than being told up front whether to\n'''
helper = '''\tvoid arm_release_guard(const InputBinding& binding)\n\t{\n\t\treleaseGuardBinding = binding;\n\t\tif (releaseGuardBinding->kind == InputBinding::Kind::JoyAxis &&\n\t\t\treleaseGuardBinding->axisMinimum == releaseGuardBinding->axisRest &&\n\t\t\treleaseGuardBinding->axisMaximum == releaseGuardBinding->axisRest)\n\t\t{\n\t\t\t// Quick Setup stores a zero-span axis until guided calibration. The\n\t\t\t// release guard is transient only, so restore the raw SDL range here\n\t\t\t// to make read() wait for the physical control to return near rest.\n\t\t\treleaseGuardBinding->axisMinimum = -32768;\n\t\t\treleaseGuardBinding->axisMaximum = 32767;\n\t\t}\n\t}\n\n\t//\n\t// Listens for any input at all rather than being told up front whether to\n'''
rep('src/overlay/input_bindings_ui.cpp', anchor, helper)
rep('src/overlay/input_bindings_ui.cpp', '\t\t\treleaseGuardBinding = prepared;\n', '\t\t\tarm_release_guard(prepared);\n')
rep('src/overlay/input_bindings_ui.cpp', '\t\t\t\t\treleaseGuardBinding = *quickSetupCandidate;\n', '\t\t\t\t\tarm_release_guard(*quickSetupCandidate);\n', count=2)


# 2) Named profile persistence: stage complete files beside the destination and
# replace only after all writes succeed. This preserves an existing good profile
# when disk/permission/close failures occur during an overwrite.
profile_anchor = '''    inline bool delete_profile(Kind kind, std::string_view rawName, std::string* error = nullptr)\n'''
profile_helpers = '''    inline std::filesystem::path staged_profile_path(const std::filesystem::path& finalPath)\n    {\n        auto staged = finalPath;\n        staged += ".tmp";\n        return staged;\n    }\n\n    inline bool commit_staged_profile(\n        const std::filesystem::path& staged,\n        const std::filesystem::path& finalPath,\n        std::string* error = nullptr)\n    {\n        auto backup = finalPath;\n        backup += ".bak";\n        std::error_code ec;\n\n        bool finalExists = std::filesystem::is_regular_file(finalPath, ec);\n        if (ec)\n        {\n            if (error) *error = "Could not inspect the existing profile: " + ec.message();\n            return false;\n        }\n\n        // Recover a previous interrupted replacement before starting another.\n        if (!finalExists && std::filesystem::is_regular_file(backup, ec) && !ec)\n        {\n            std::filesystem::rename(backup, finalPath, ec);\n            if (ec)\n            {\n                if (error) *error = "Could not recover the previous profile backup: " + ec.message();\n                return false;\n            }\n            finalExists = true;\n        }\n        else if (ec)\n        {\n            if (error) *error = "Could not inspect the profile backup: " + ec.message();\n            return false;\n        }\n\n        if (finalExists)\n        {\n            std::filesystem::remove(backup, ec);\n            if (ec)\n            {\n                if (error) *error = "Could not clear a stale profile backup: " + ec.message();\n                return false;\n            }\n            std::filesystem::rename(finalPath, backup, ec);\n            if (ec)\n            {\n                if (error) *error = "Could not preserve the existing profile before overwrite: " + ec.message();\n                return false;\n            }\n        }\n\n        std::filesystem::rename(staged, finalPath, ec);\n        if (ec)\n        {\n            const std::string replaceError = ec.message();\n            if (finalExists)\n            {\n                std::error_code restoreEc;\n                std::filesystem::rename(backup, finalPath, restoreEc);\n                if (restoreEc)\n                {\n                    if (error) *error = "Could not install the new profile (" + replaceError +\n                        ") and could not restore the backup (" + restoreEc.message() + ").";\n                    return false;\n                }\n            }\n            if (error) *error = "Could not install the completed profile: " + replaceError;\n            return false;\n        }\n\n        if (finalExists)\n        {\n            std::error_code ignored;\n            std::filesystem::remove(backup, ignored);\n        }\n        return true;\n    }\n\n    inline bool delete_profile(Kind kind, std::string_view rawName, std::string* error = nullptr)\n'''
rep('src/wheel_profile_store.hpp', profile_anchor, profile_helpers)

rep('src/wheel_profile_store.hpp', '''        file.flush();\n        if (!file)\n        {\n            if (error) *error = "Failed while writing wheel-specific input options.";\n            return false;\n        }\n        return true;\n''', '''        file.flush();\n        if (!file)\n        {\n            if (error) *error = "Failed while writing wheel-specific input options.";\n            file.close();\n            return false;\n        }\n        file.close();\n        if (file.fail())\n        {\n            if (error) *error = "Failed while closing wheel-specific input options.";\n            return false;\n        }\n        return true;\n''')

old_ffb_save = '''    inline bool save_ffb_profile(std::string_view rawName, std::string* error = nullptr)\n    {\n        auto path = profile_path(Kind::ForceFeedback, rawName, error);\n        if (!path)\n            return false;\n\n        std::ofstream file(*path, std::ios::out | std::ios::trunc);\n        if (!file)\n        {\n            if (error) *error = "Could not open FFB profile for writing.";\n            return false;\n        }\n        file << "# OutRun2006Tweaks named force-feedback feel profile.\\n";\n        file << "# DeviceName/DeviceGuid and diagnostic logging are intentionally not stored here.\\n\\n";\n        file << "[Profile]\\nType = ForceFeedback\\nVersion = 1\\n\\n";\n        file << "[WheelFFB]\\n";\n        for (const Settings::SettingBase* setting : ffb_settings())\n            file << setting->key() << " = " << setting->to_string() << "\\n";\n        file.flush();\n        if (!file)\n        {\n            if (error) *error = "Failed while writing FFB profile.";\n            return false;\n        }\n        return true;\n    }\n'''
new_ffb_save = '''    inline bool save_ffb_profile(std::string_view rawName, std::string* error = nullptr)\n    {\n        auto path = profile_path(Kind::ForceFeedback, rawName, error);\n        if (!path)\n            return false;\n\n        const auto staged = staged_profile_path(*path);\n        {\n            std::error_code ignored;\n            std::filesystem::remove(staged, ignored);\n        }\n        std::ofstream file(staged, std::ios::out | std::ios::trunc);\n        if (!file)\n        {\n            if (error) *error = "Could not open staged FFB profile for writing.";\n            return false;\n        }\n        file << "# OutRun2006Tweaks named force-feedback feel profile.\\n";\n        file << "# DeviceName/DeviceGuid and diagnostic logging are intentionally not stored here.\\n\\n";\n        file << "[Profile]\\nType = ForceFeedback\\nVersion = 1\\n\\n";\n        file << "[WheelFFB]\\n";\n        for (const Settings::SettingBase* setting : ffb_settings())\n            file << setting->key() << " = " << setting->to_string() << "\\n";\n        file.flush();\n        if (!file)\n        {\n            if (error) *error = "Failed while writing staged FFB profile.";\n            file.close();\n            std::error_code ignored;\n            std::filesystem::remove(staged, ignored);\n            return false;\n        }\n        file.close();\n        if (file.fail())\n        {\n            if (error) *error = "Failed while closing staged FFB profile.";\n            std::error_code ignored;\n            std::filesystem::remove(staged, ignored);\n            return false;\n        }\n        if (!commit_staged_profile(staged, *path, error))\n        {\n            std::error_code ignored;\n            std::filesystem::remove(staged, ignored);\n            return false;\n        }\n        return true;\n    }\n'''
rep('src/wheel_profile_store.hpp', old_ffb_save, new_ffb_save)

old_input_save = '''\t\t\telse if (auto profilePath = WheelProfileStore::profile_path(\n\t\t\t\tWheelProfileStore::Kind::Input, requestedName, &error))\n\t\t\t{\n\t\t\t\tif (!manager.saveBindingIni(*profilePath))\n\t\t\t\t{\n\t\t\t\t\tpersistenceStatus = "Could not save wheel profile bindings.";\n\t\t\t\t}\n\t\t\t\telse if (!WheelProfileStore::append_input_options(*profilePath, &error))\n\t\t\t\t{\n\t\t\t\t\tstd::error_code ignored;\n\t\t\t\t\tstd::filesystem::remove(*profilePath, ignored);\n\t\t\t\t\tpersistenceStatus = error;\n\t\t\t\t}\n\t\t\t\telse\n\t\t\t\t{\n'''
new_input_save = '''\t\t\telse if (auto profilePath = WheelProfileStore::profile_path(\n\t\t\t\tWheelProfileStore::Kind::Input, requestedName, &error))\n\t\t\t{\n\t\t\t\tconst auto stagedPath = WheelProfileStore::staged_profile_path(*profilePath);\n\t\t\t\t{\n\t\t\t\t\tstd::error_code ignored;\n\t\t\t\t\tstd::filesystem::remove(stagedPath, ignored);\n\t\t\t\t}\n\t\t\t\tif (!manager.saveBindingIni(stagedPath))\n\t\t\t\t{\n\t\t\t\t\tpersistenceStatus = "Could not stage wheel profile bindings.";\n\t\t\t\t}\n\t\t\t\telse if (!WheelProfileStore::append_input_options(stagedPath, &error))\n\t\t\t\t{\n\t\t\t\t\tstd::error_code ignored;\n\t\t\t\t\tstd::filesystem::remove(stagedPath, ignored);\n\t\t\t\t\tpersistenceStatus = error;\n\t\t\t\t}\n\t\t\t\telse if (!WheelProfileStore::commit_staged_profile(stagedPath, *profilePath, &error))\n\t\t\t\t{\n\t\t\t\t\tstd::error_code ignored;\n\t\t\t\t\tstd::filesystem::remove(stagedPath, ignored);\n\t\t\t\t\tpersistenceStatus = error;\n\t\t\t\t}\n\t\t\t\telse\n\t\t\t\t{\n'''
rep('src/overlay/input_bindings_ui.cpp', old_input_save, new_input_save)


# 3) FFB revert baseline: these paths persist the whole user.ini and clear the
# dirty flag, so their successful write must also become the new revert point.
rep('src/overlay/wheel_setup_ui.cpp', '''            if (Settings::write(Module::UserIniPath))\n            {\n                ffbDirty_ = false;\n                status_ = "Saved to OutRun2006Tweaks.user.ini";\n''', '''            if (Settings::write(Module::UserIniPath))\n            {\n                ffbDirty_ = false;\n                capture_saved_ffb();\n                status_ = "Saved to OutRun2006Tweaks.user.ini";\n''')
rep('src/overlay/wheel_setup_ui.cpp', '''                if (Settings::write(Module::UserIniPath))\n                {\n                    ffbDirty_ = false;\n                    status_ = "Selected FFB output and saved its exact DirectInput GUID. The FFB engine will reinitialize automatically on the next gameplay update.";\n''', '''                if (Settings::write(Module::UserIniPath))\n                {\n                    ffbDirty_ = false;\n                    capture_saved_ffb();\n                    status_ = "Selected FFB output and saved its exact DirectInput GUID. The FFB engine will reinitialize automatically on the next gameplay update.";\n''')


# Regression guards for all defects found in this 10-pass debug review.
verify = read('tools/verify_wheel_ffb_current.py')
marker = '# debug10-regression-guards\n'
if marker not in verify:
    verify += '''\n# debug10-regression-guards\nreq(bind_ui, 'void arm_release_guard(const InputBinding& binding)', 'Quick Setup owns a raw-axis release guard independent of calibration span')\nreq(bind_ui, 'releaseGuardBinding->axisMinimum = -32768;', 'zero-span Quick Setup axis gets transient release range')\nif bind_ui.count('arm_release_guard(*quickSetupCandidate);') != 2:\n    raise SystemExit('CURRENT VERIFY FAILED [Quick Setup confirm/retry both arm the axis release guard]')\nprint('OK [Quick Setup confirm/retry both arm the axis release guard]')\nforbid(bind_ui, 'releaseGuardBinding = *quickSetupCandidate;', 'Quick Setup never uses zero-span candidate directly as release guard')\nreq(profiles, 'commit_staged_profile(', 'named profile writes use staged replacement')\nreq(bind_ui, 'WheelProfileStore::staged_profile_path(*profilePath)', 'input profile is fully staged before overwrite')\nreq(bind_ui, 'WheelProfileStore::commit_staged_profile(stagedPath, *profilePath, &error)', 'input profile overwrite preserves previous file until staged write completes')\nreq(profiles, 'const auto staged = staged_profile_path(*path);', 'FFB profile is fully staged before overwrite')\nreq(profiles, 'Failed while closing staged FFB profile.', 'FFB profile close failures are reported')\nreq(profiles, 'Failed while closing wheel-specific input options.', 'input profile option close failures are reported')\nreq(wheel_ui, 'capture_saved_ffb();\\n                status_ = "Saved to OutRun2006Tweaks.user.ini";', 'legacy full user.ini save refreshes FFB revert baseline')\nreq(wheel_ui, 'capture_saved_ffb();\\n                    status_ = "Selected FFB output and saved its exact DirectInput GUID.', 'FFB output selection refreshes revert baseline after full user.ini persistence')\n'''
    write('tools/verify_wheel_ffb_current.py', verify)

print('10-pass debug fixes applied')
