from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

def read(path):
    return (ROOT / path).read_text(encoding='utf-8')

def write(path, text):
    (ROOT / path).write_text(text, encoding='utf-8', newline='\n')

def rep(path, old, new, count=1):
    text = read(path)
    actual = text.count(old)
    if actual != count:
        raise SystemExit(f'{path}: expected {count} matches, found {actual}: {old[:140]!r}')
    write(path, text.replace(old, new, count))

# Fresh raw axes captured by Quick Setup have only a rest/centre sample. Mark
# their endpoints unmeasured so the completion screen cannot mistake defaults
# for real calibration.
rep('src/overlay/input_bindings_ui.cpp', '''\t\tconst auto commit = [&](const InputBinding& binding)\n\t\t{\n\t\t\tconst std::string conflicts = binding_conflicts(binding, bindTarget);\n\t\t\tif (!conflicts.empty())\n\t\t\t\tpersistenceStatus = "Note: this control is also bound to " + conflicts + ".";\n\t\t\tif (quickSetupActive)\n\t\t\t{\n\t\t\t\tquickSetupCandidate = binding;\n\t\t\t\treturn;\n\t\t\t}\n\t\t\telse if (bindIndex >= 0 && bindIndex < int(bindings.size()))\n\t\t\t\tbindings[bindIndex] = binding;\n\t\t\telse\n\t\t\t\taction.add(binding);\n\n\t\t\treleaseGuardBinding = binding;\n''', '''\t\tconst auto commit = [&](const InputBinding& binding)\n\t\t{\n\t\t\tInputBinding prepared = binding;\n\t\t\tif (quickSetupActive && prepared.kind == InputBinding::Kind::JoyAxis)\n\t\t\t{\n\t\t\t\tprepared.axisMinimum = prepared.axisRest;\n\t\t\t\tprepared.axisMaximum = prepared.axisRest;\n\t\t\t}\n\n\t\t\tconst std::string conflicts = binding_conflicts(prepared, bindTarget);\n\t\t\tif (!conflicts.empty())\n\t\t\t\tpersistenceStatus = "Note: this control is also bound to " + conflicts + ".";\n\t\t\tif (quickSetupActive)\n\t\t\t{\n\t\t\t\tquickSetupCandidate = prepared;\n\t\t\t\treturn;\n\t\t\t}\n\t\t\telse if (bindIndex >= 0 && bindIndex < int(bindings.size()))\n\t\t\t\tbindings[bindIndex] = prepared;\n\t\t\telse\n\t\t\t\taction.add(prepared);\n\n\t\t\treleaseGuardBinding = prepared;\n''')

# Quick Setup should actually complete core raw-axis calibration before the
# one-click Save & Drive path is enabled.
rep('src/overlay/input_bindings_ui.cpp', '''\t\tconst bool guidedCalibrationReady =\n\t\t\taxis_calibrated({ Vol, int(ADChannel::Steering) }) &&\n\t\t\taxis_calibrated({ Vol, int(ADChannel::Acceleration) }) &&\n\t\t\taxis_calibrated({ Vol, int(ADChannel::Brake) });\n\t\tif (!guidedCalibrationReady)\n\t\t\tImGui::TextColored(ImVec4(1.0f, 0.70f, 0.20f, 1.0f),\n\t\t\t\t"Raw wheel/pedal axes still need calibration; Save & Drive remains available if you intentionally want the current ranges.");\n\n\t\tImGui::Spacing();\n\t\tif (ImGui::Button("Save & Drive"))\n\t\t{\n''', '''\t\tconst Selection steeringSelection{ Vol, int(ADChannel::Steering) };\n\t\tconst Selection acceleratorSelection{ Vol, int(ADChannel::Acceleration) };\n\t\tconst Selection brakeSelection{ Vol, int(ADChannel::Brake) };\n\t\tconst bool coreControlsPresent =\n\t\t\t!action_for(steeringSelection).bindings().empty() &&\n\t\t\t!action_for(acceleratorSelection).bindings().empty() &&\n\t\t\t!action_for(brakeSelection).bindings().empty();\n\t\tconst bool guidedCalibrationReady =\n\t\t\taxis_calibrated(steeringSelection) &&\n\t\t\taxis_calibrated(acceleratorSelection) &&\n\t\t\taxis_calibrated(brakeSelection);\n\t\tconst bool readyToSaveAndDrive = coreControlsPresent && guidedCalibrationReady;\n\t\tif (!coreControlsPresent)\n\t\t\tImGui::TextColored(ImVec4(1.0f, 0.70f, 0.20f, 1.0f),\n\t\t\t\t"Steering, accelerator and brake need bindings before Save & Drive.");\n\t\telse if (!guidedCalibrationReady)\n\t\t\tImGui::TextColored(ImVec4(1.0f, 0.70f, 0.20f, 1.0f),\n\t\t\t\t"Calibrate the raw wheel/pedal axes above before Save & Drive.");\n\n\t\tImGui::Spacing();\n\t\tif (!readyToSaveAndDrive) ImGui::BeginDisabled();\n\t\tconst bool saveAndDrive = ImGui::Button("Save & Drive");\n\t\tif (!readyToSaveAndDrive) ImGui::EndDisabled();\n\t\tif (saveAndDrive)\n\t\t{\n''')

rep('src/overlay/input_bindings_ui.cpp', '#include "wheel_profile_store.hpp"\n', '#include "wheel_profile_store.hpp"\n#include "wheel_ffb_runtime.hpp"\n')

# Target only the LOAD path. Saving the current profile does not change wheels
# and should not force the user to re-run the direction test.
rep('src/overlay/input_bindings_ui.cpp', '''\t\t\t\t\tconst bool optionsSaved = Settings::write(Module::UserIniPath);\n\t\t\t\t\tunsavedChanges = !currentSaved;\n\t\t\t\t\tpersistenceStatus = currentSaved && optionsSaved\n\t\t\t\t\t\t? "Wheel profile loaded and made current: " + *selected\n''', '''\t\t\t\t\tconst bool optionsSaved = Settings::write(Module::UserIniPath);\n\t\t\t\t\tWheelFFB_ResetDirectionTest();\n\t\t\t\t\tunsavedChanges = !currentSaved;\n\t\t\t\t\tpersistenceStatus = currentSaved && optionsSaved\n\t\t\t\t\t\t? "Wheel profile loaded and made current: " + *selected\n''')

# Direction-test readiness belongs to the physical output wheel.
rep('src/wheel_ffb_runtime.hpp', 'void WheelFFB_RequestSettingsTransition();\n', 'void WheelFFB_RequestSettingsTransition();\nvoid WheelFFB_ResetDirectionTest();\n')
rep('src/hooks_wheel_ffb.cpp', '''                    selectedConfiguredGuid_ = guidNow;\n                    selectedConfiguredName_ = nameNow;\n                    request_device_reinitialize("configured wheel identity changed", S_OK);\n''', '''                    selectedConfiguredGuid_ = guidNow;\n                    selectedConfiguredName_ = nameNow;\n                    directionTested_ = false;\n                    request_device_reinitialize("configured wheel identity changed", S_OK);\n''')
rep('src/hooks_wheel_ffb.cpp', '''        void settings_transition()\n        {\n''', '''        void reset_direction_test()\n        {\n            directionTested_ = false;\n        }\n\n        void settings_transition()\n        {\n''')
rep('src/hooks_wheel_ffb.cpp', '''void WheelFFB_RequestSettingsTransition()\n{\n    gWheelFFB.settings_transition();\n}\n\nWheelFFBHeadroomSnapshot WheelFFB_GetHeadroomSnapshot()\n''', '''void WheelFFB_RequestSettingsTransition()\n{\n    gWheelFFB.settings_transition();\n}\n\nvoid WheelFFB_ResetDirectionTest()\n{\n    gWheelFFB.reset_direction_test();\n}\n\nWheelFFBHeadroomSnapshot WheelFFB_GetHeadroomSnapshot()\n''')

# F11 cleanup and complete Revert baseline.
rep('src/overlay/wheel_setup_ui.cpp', '#include <cstdio>\n#include <cstdint>\n#include <cstring>\n', '#include <cstdio>\n#include <cstring>\n')
rep('src/overlay/wheel_setup_ui.cpp', '''            bool responseCorrection = false;\n            float global = 0.70f;\n''', '''            bool responseCorrection = false;\n            bool debugLog = true;\n            bool telemetry = false;\n            float global = 0.70f;\n''')
rep('src/overlay/wheel_setup_ui.cpp', '''            savedFfb_.responseCorrection = Settings::WheelFFBResponseCorrection;\n            savedFfb_.global = Settings::WheelFFBGlobalStrength;\n''', '''            savedFfb_.responseCorrection = Settings::WheelFFBResponseCorrection;\n            savedFfb_.debugLog = Settings::WheelFFBDebugLog;\n            savedFfb_.telemetry = Settings::WheelFFBTelemetry;\n            savedFfb_.global = Settings::WheelFFBGlobalStrength;\n''')
rep('src/overlay/wheel_setup_ui.cpp', '''            Settings::WheelFFBResponseCorrection = savedFfb_.responseCorrection;\n            Settings::WheelFFBGlobalStrength = savedFfb_.global;\n''', '''            Settings::WheelFFBResponseCorrection = savedFfb_.responseCorrection;\n            Settings::WheelFFBDebugLog = savedFfb_.debugLog;\n            Settings::WheelFFBTelemetry = savedFfb_.telemetry;\n            Settings::WheelFFBGlobalStrength = savedFfb_.global;\n''')
rep('src/overlay/wheel_setup_ui.cpp', '''                        const bool currentSaved = Settings::write(Module::UserIniPath);\n                        ffbDirty_ = !currentSaved;\n                        status_ = currentSaved\n                            ? "FFB profile saved: " + requested\n''', '''                        const bool currentSaved = Settings::write(Module::UserIniPath);\n                        ffbDirty_ = !currentSaved;\n                        if (currentSaved)\n                            capture_saved_ffb();\n                        status_ = currentSaved\n                            ? "FFB profile saved: " + requested\n''')
rep('src/overlay/wheel_setup_ui.cpp', '''                Settings::WheelFFBDeviceName = info.name;\n                Settings::WheelFFBDeviceGuid = info.guidKey;\n                if (Settings::write(Module::UserIniPath))\n''', '''                const bool changedOutput =\n                    lower_identity(Settings::WheelFFBDeviceGuid.get()) != info.guidKey ||\n                    Settings::WheelFFBDeviceName.get() != info.name;\n                Settings::WheelFFBDeviceName = info.name;\n                Settings::WheelFFBDeviceGuid = info.guidKey;\n                if (changedOutput)\n                    WheelFFB_ResetDirectionTest();\n                if (Settings::write(Module::UserIniPath))\n''')
rep('src/overlay/wheel_setup_ui.cpp', '''                readiness("Menu controls", menuReady);\n                ImGui::SameLine(); readiness("FFB device", ffbStatus.initialized || !Settings::WheelFFBDeviceGuid.get().empty());\n                ImGui::SameLine(); readiness("Direction test", ffbStatus.directionTested);\n''', '''                readiness("Menu controls", menuReady);\n                const bool ffbReady = !Settings::WheelFFBEnable || ffbStatus.initialized;\n                ImGui::SameLine(); readiness(Settings::WheelFFBEnable ? "FFB device" : "FFB disabled", ffbReady);\n                ImGui::SameLine(); readiness("Direction test", !Settings::WheelFFBEnable || ffbStatus.directionTested);\n''')
rep('src/overlay/wheel_setup_ui.cpp', '''                ImGui::TextDisabled("Dynamic effect capability: Constant %s, POLAR direction %s, Spring %s, Damper %s, Sine %s",\n                    ffbStatus.constantDynamic ? "yes" : "no",\n                    ffbStatus.polarDirectionDynamic ? "yes" : "no",\n                    ffbStatus.springDynamic ? "yes" : "no",\n                    ffbStatus.damperDynamic ? "yes" : "no",\n                    ffbStatus.periodicDynamic ? "yes" : "no");\n''', '''                const auto capability_text = [](bool known, bool dynamic)\n                {\n                    return !known ? "unknown" : (dynamic ? "yes" : "no");\n                };\n                ImGui::TextDisabled("Dynamic effect capability: Constant %s, POLAR direction %s, Spring %s, Damper %s, Sine %s",\n                    capability_text(ffbStatus.constantCapsKnown, ffbStatus.constantDynamic),\n                    capability_text(ffbStatus.constantCapsKnown, ffbStatus.polarDirectionDynamic),\n                    capability_text(ffbStatus.springCapsKnown, ffbStatus.springDynamic),\n                    capability_text(ffbStatus.damperCapsKnown, ffbStatus.damperDynamic),\n                    capability_text(ffbStatus.periodicCapsKnown, ffbStatus.periodicDynamic));\n''')

verify = read('tools/verify_wheel_ffb_current.py')
if '# final-postfix-regression-guards\n' not in verify:
    verify += '''\n# final-postfix-regression-guards\nreq(bind_ui, 'prepared.axisMinimum = prepared.axisRest;', 'fresh Quick Setup raw axes start uncalibrated')\nreq(bind_ui, 'const bool readyToSaveAndDrive = coreControlsPresent && guidedCalibrationReady;', 'Quick Setup gates Save & Drive on core controls and raw calibration')\nreq(bind_ui, 'WheelFFB_ResetDirectionTest();', 'loading a wheel profile invalidates the old direction test')\nreq(runtime, 'void WheelFFB_ResetDirectionTest();', 'direction-test reset API')\nreq(ffb, 'directionTested_ = false;\\n                    request_device_reinitialize("configured wheel identity changed", S_OK);', 'external FFB device identity changes invalidate direction test')\nreq(wheel_ui, 'if (changedOutput)\\n                    WheelFFB_ResetDirectionTest();', 'F11 FFB device selection invalidates direction test immediately')\nreq(wheel_ui, 'bool debugLog = true;', 'FFB revert baseline includes diagnostic logging')\nreq(wheel_ui, 'savedFfb_.telemetry = Settings::WheelFFBTelemetry;', 'FFB revert baseline includes telemetry')\nreq(wheel_ui, 'if (currentSaved)\\n                            capture_saved_ffb();', 'saving a named FFB profile refreshes the revert baseline')\nreq(wheel_ui, 'return !known ? "unknown" : (dynamic ? "yes" : "no");', 'FFB capability UI distinguishes unknown from yes')\nreq(wheel_ui, 'const bool ffbReady = !Settings::WheelFFBEnable || ffbStatus.initialized;', 'Ready checklist does not treat a disconnected saved GUID as ready')\nforbid(wheel_ui, '#include <cstdint>\\n#include <cstdio>\\n#include <cstdint>', 'duplicate cstdint include')\n'''
    write('tools/verify_wheel_ffb_current.py', verify)

print('corrected final FFB/UI postfix applied')
