from pathlib import Path

p = Path('tools/verify_wheel_ffb_current.py')
text = p.read_text(encoding='utf-8')
text = text.replace("req(ui, 'Ready to Drive'", "req(wheel_ui, 'Ready to Drive'")
text = text.replace("req(ui, 'FFB Runtime Status'", "req(wheel_ui, 'FFB Runtime Status'")
text = text.replace("req(ui, 'recommended: steering device'", "req(wheel_ui, 'recommended: steering device'")
text = text.replace("req(ui, 'Revert unsaved FFB'", "req(wheel_ui, 'Revert unsaved FFB'")
text = text.replace("req(ui, 'Recent FFB Pipeline'", "req(wheel_ui, 'Recent FFB Pipeline'")
text = text.replace("req(ui, 'Countersteer Release Rate'", "req(wheel_ui, 'Countersteer Release Rate'")
text = text.replace("req(bindings_ui, 'LISTENING...##addBinding'", "req(bind_ui, 'LISTENING...##addBinding'")
text = text.replace("req(bindings_ui, 'const bool listeningHere'", "req(bind_ui, 'const bool listeningHere'")
text = text.replace("req(bindings_ui, 'binding_conflicts'", "req(bind_ui, 'binding_conflicts'")
text = text.replace("req(bindings_ui, 'Guided axis calibration'", "req(bind_ui, 'Guided axis calibration'")
p.write_text(text, encoding='utf-8', newline='\n')
print('fixed verifier source variable names')
