    for yy,xx in zip(*np.where(tbt)):
        off=(yy*bx+xx)*BLOCK; tpay[off:off+BLOCK]=tb[128+off:128+off+BLOCK]
    candidate=header+bytes(tpay)
    if sha(candidate)!=EXPECTED_CANDIDATE_SHA: raise SystemExit(f'candidate fingerprint drift {sha(candidate)}')
    CAND.parent.mkdir(parents=True,exist_ok=True); CAND.write_bytes(candidate); cand=np.array(Image.open(CAND).convert('RGBA'),dtype=np.uint8)
    allowed=np.zeros((H,W),bool)
    for yy,xx in zip(*np.where(tbt)): allowed[yy*4:min(H,yy*4+4),xx*4:min(W,xx*4+4)]=True
    protected=np.ones((H,W),bool)
    for _,_,_,_,rect,_,_,_,_ in REGIONS:
        x,yb,w,h=rect; y=H-(yb+h); protected[y:y+h,x:x+w]=False
    changed=np.any(cand!=src,axis=2); ach=cand[:,:,3]!=src[:,:,3]
    if changed[~allowed].any() or ach[~allowed].any() or changed[protected].any(): raise SystemExit('decoded zero-pixel/protected gate fail')
    for m,r in zip(metrics,REGIONS):
        idx,_,_,_,rect,_,safe,_,_=r; x,yb,w,h=rect; y=H-(yb+h); disp=cand[y:y+h,x:x+w][::-1]; ys,xs=np.where(disp[:,:,3]>0); bb=[int(xs.min()),int(ys.min()),int(xs.max()),int(ys.max())]; m['localized_bbox_readable_local_decoded_final']=bb; m['safe_margins_ltrb_decoded_final']=[bb[0]-safe[0],bb[1]-safe[1],safe[2]-bb[2],safe[3]-bb[3]]; m['containment_decoded_final']='PASS' if inside(bb,safe) else 'FAIL'; m['decoded_final_alpha_pixels']=int((disp[:,:,3]>0).sum())
        if m['containment_decoded_final']!='PASS': raise SystemExit(f'decoded containment {idx}')
        if int((clean_dec[y:y+h,x:x+w,3]>0).sum())!=0: raise SystemExit(f'clean alpha residue {idx}')
    REVIEW.mkdir(parents=True,exist_ok=True); cand_display=np.flipud(cand).copy(); clean_display=np.flipud(clean_dec).copy(); letter_display=np.flipud(lettering).copy(); removal_display=np.flipud(removal).copy(); allowed_display=np.flipud(allowed).copy()
    save_rgba(src_display,REVIEW/'source_display.png'); save_rgba(clean_display,REVIEW/'clean_plate_display.png'); save_rgba(cand_display,REVIEW/'candidate_display.png'); save_rgba(letter_display,REVIEW/'lettering_display.png')
    Image.fromarray((removal_display*255).astype(np.uint8),'L').save(REVIEW/'source_text_mask_display.png',optimize=False); Image.fromarray((~allowed_display*255).astype(np.uint8),'L').save(REVIEW/'protected_mask_display.png',optimize=False)
    diff=np.zeros_like(src_display); diff[np.any(src_display!=cand_display,axis=2)]=[255,255,255,255]; save_rgba(diff,REVIEW/'diff_display.png')
    label=ImageFont.truetype(str(fp),20,index=fi); panel=Image.new('RGBA',(W*3,H+34),(24,24,24,255)); pd=ImageDraw.Draw(panel)
    for i,(name,a) in enumerate([('ENGLISH SOURCE',src_display),('CLEAN PLATE',clean_display),('KOREAN CANDIDATE',cand_display)]): pd.text((i*W+8,5),name,font=label,fill=(255,255,255,255)); panel.alpha_composite(Image.fromarray(a,'RGBA'),(i*W,34))
    panel.save(REVIEW/'comparison.png',optimize=False)
    rows=[]; lfont=ImageFont.truetype(str(fp),18,index=fi)
    for r in REGIONS:
        idx,_,en,ko,rect,srcbb,_,_,_=r; x,yb,w,h=rect; y=H-(yb+h); x1,y1,x2,y2=srcbb; pad=8; xa=max(0,x+x1-pad); ya=max(0,(H-(yb+h))+y1-pad); xb=min(W,x+x2+pad+1); yb2=min(H,(H-(yb+h))+y2+pad+1); s=dark(src_display[ya:yb2,xa:xb]).resize(((xb-xa)*2,(yb2-ya)*2),Image.Resampling.NEAREST); d=dark(cand_display[ya:yb2,xa:xb]).resize(((xb-xa)*2,(yb2-ya)*2),Image.Resampling.NEAREST); row=Image.new('RGBA',(s.width+d.width,max(s.height,d.height)+30),(20,20,20,255)); dr=ImageDraw.Draw(row); dr.text((6,4),f'SOURCE {en}',font=lfont,fill='white'); dr.text((s.width+6,4),f'KOREAN {ko}',font=lfont,fill='white'); row.alpha_composite(s,(0,30)); row.alpha_composite(d,(s.width,30)); rows.append(row)
    ec=Image.new('RGBA',(max(r.width for r in rows),sum(r.height for r in rows)),(20,20,20,255)); yy=0
    for r in rows: ec.alpha_composite(r,(0,yy)); yy+=r.height
    ec.save(REVIEW/'element_comparison.png',optimize=False)
    prompt={'contract':'outrun-first-pass-edit-v2','task_id':TASK_ID,'wave_id':WAVE_ID,'queue_index':INDEX,'asset':ASSET,'source':{'archive':'OR2-HD-GUI-v0.25.10a.zip','archive_sha256':ARCHIVE_SHA,'member':'textures/load/spr_sprani_sumo_fe_cvt_Exst/DDF0392A_256x512.dds','sha256':SOURCE_SHA,'dimensions':[W,H],'format':'DXT5','mipmaps':1,'raw_to_readable':'flip_y'},'accepted_precandidate_lineage':{'a00215_result_sha':'64e756e0cfba3b141a2e94915168f709a1a226a3','c149_q00047_result_sha':'149ce00855248574d0813d34ba34da2a1e336f17','production_readiness':'RENDER_READY'},'font':{'identifier':'NotoSansCJK-Bold.ttc#1 Noto Sans CJK KR Bold','sha256':EXPECTED_FONT_SHA},'elements':[{'region_index':m['region_index'],'sprite':m['sprite'],'source':m['source'],'approved_korean':m['korean'],'source_effect_bbox_readable_local':m['source_effect_bbox_readable_local'],'candidate_safe_bbox_readable_local':m['candidate_safe_bbox_readable_local'],'candidate_fill_rgb':m['candidate_fill_rgb'],'font_size_px':m['font_size_px']} for m in metrics],'instructions':['Use only exact canonical DDF0392A source and C149/Q00047 accepted masks/clean plate/safe bboxes.','Preserve 19 protected song-title/Ferrari-model regions byte-for-byte at BC3 block level.','Build lettering in readable coordinates then flip vertically to raw DDS.','Use upright heavy condensed sans with flat source-sampled dark-gray fill; no outline/shadow/glow.','Use Noto Sans CJK KR Bold natively; no flattened-raster resize or slant transform.','Left-align inside final 2px-safe bbox with an additional internal pixel.','Encode DXT5 mip1 with exact original 128-byte header; patch only changed BC3 blocks.','Reject any decoded-final bbox escape, protected change, outside-edit change, wrong orientation, broken Hangul or source residue.'],'raster_resampling':'NOT_USED','source_slant_direction':'none','candidate_slant_direction':'none'}
    pb=(json.dumps(prompt,ensure_ascii=False,indent=2)+'\n').encode(); REVIEW.joinpath('generation_prompt.json').write_bytes(pb)
    if sha(pb)!=EXPECTED_PROMPT_SHA: raise SystemExit(f'prompt fingerprint drift {sha(pb)}')
    candidate_sha=sha(candidate)
    qa={'schema_version':14,'schema':'outrun-a00221-index222-v2-production-v1','task_id':TASK_ID,'wave_id':WAVE_ID,'lane':'LOCALIZATION_A','queue_index':INDEX,'asset':ASSET,'recorded_at_kst':now,'base_head_sha':base,
        'source':{'transport':'pinned_release_exact_canonical_source','archive':'OR2-HD-GUI-v0.25.10a.zip','archive_sha256':ARCHIVE_SHA,'member':'textures/load/spr_sprani_sumo_fe_cvt_Exst/DDF0392A_256x512.dds','sha256':SOURCE_SHA,'bytes':len(sb),'header_128_sha256':sha(header),'decoded_raw_rgba_sha256':sha(src.tobytes()),'decoded_display_rgba_sha256':sha(src_display.tobytes()),'dimensions':[W,H],'format':'DXT5','mipmaps':1,'raw_to_readable':'flip_y','canonical_inventory_match':True},
        'accepted_precandidate_lineage':{'a00215_result_sha':'64e756e0cfba3b141a2e94915168f709a1a226a3','c149_q00047_result_sha':'149ce00855248574d0813d34ba34da2a1e336f17','production_readiness':'RENDER_READY'},
        'clean_plate':{'accepted_c_replay':'PASS_Q00047','removal_mask_pixels':int(removal.sum()),'clean_plate_preencode_raw_rgba_sha256':sha(clean.tobytes()),'clean_plate_encoded_roundtrip_raw_rgba_sha256':sha(clean_dec.tobytes()),'clean_plate_encoded_roundtrip_display_rgba_sha256':sha(clean_display.tobytes()),'changed_pixels_outside_removal_block_mask':0,'alpha_changed_pixels_outside_removal_block_mask':0,'localized_regions_alpha_after_encoded_clean_plate':0,'protected_regions_unchanged':True},
        'render':{'contract':'outrun-first-pass-edit-v2','font_identifier':'NotoSansCJK-Bold.ttc#1 Noto Sans CJK KR Bold','font_sha256':EXPECTED_FONT_SHA,'source_transform':'flip_y','source_baseline_vector_readable':[1,0],'candidate_baseline_vector_readable':[1,0],'source_signed_slant_angle_deg':0.0,'candidate_signed_slant_angle_deg':0.0,'source_slant_direction':'none','candidate_slant_direction':'none','flattened_raster_resize':'NOT_USED','metrics':metrics},
        'candidate':{'repo_path':'localization/graphics/hd_candidates/textures/load/spr_sprani_sumo_fe_cvt_Exst/DDF0392A_256x512.dds','sha256':candidate_sha,'bytes':len(candidate),'header_128_exact':candidate[:128]==sb[:128],'format':'DXT5','mipmaps':1,'changed_bc3_blocks':int(tbt.sum()),'total_bc3_blocks':int(bx*by),'changed_pixels':int(changed.sum()),'changed_pixels_outside_allowed_edit_mask':0,'alpha_changed_pixels_total':int(ach.sum()),'alpha_changed_pixels_outside_allowed_edit_mask':0,'changed_pixels_in_protected_regions':0,'candidate_letter_pixels_decoded':sum(m['decoded_final_alpha_pixels'] for m in metrics),'decoded_raw_rgba_sha256':sha(cand.tobytes()),'decoded_display_rgba_sha256':sha(cand_display.tobytes()),'orientation':'PASS_FLIP_Y_RAW_TO_READABLE','safe_bbox_containment':'PASS_2PX_INSET_ALL_6','one_pixel_overflow':0,'raster_resampling':'NOT_USED'},
        'visual_review_contract':{'full_atlas':'comparison.png','per_element_readable_zoom':'element_comparison.png','source_clean_candidate_set':['source_display.png','clean_plate_display.png','candidate_display.png'],'source_mask':'source_text_mask_display.png','protected_mask':'protected_mask_display.png','lettering':'lettering_display.png','diff':'diff_display.png','status':'PRODUCER_VISUAL_REVIEW_PASS_REUSED_EXACT_DETERMINISTIC_FINGERPRINT_PENDING_INDEPENDENT_C','manual_review_fingerprint':EXPECTED_CANDIDATE_SHA,'manual_review_findings':{'source_vs_candidate':'PASS_ALL_6_TRANSLATIONS_VISIBLE_AND_CORRECT','broken_hangul':'NONE_OBSERVED','clipping_or_overlap':'NONE_OBSERVED','source_english_residue_localized_regions':'NONE_OBSERVED','protected_song_and_model_text_damage':'NONE_OBSERVED','wrong_image_replacement':'NONE_OBSERVED','resolution_loss':'NONE_OBSERVED','raw_orientation':'PASS_VERTICAL_FLIP_MATCHES_SOURCE_STORAGE','style':'PASS_UPRIGHT_HEAVY_SANS_FLAT_DARK_GRAY_NO_ADDED_EFFECTS'}},
        'static_qa':'PASS_PRODUCER_MACHINE_AND_VISUAL_PENDING_INDEPENDENT_C','candidate_dds_modified':True,'shared_state_modified':False,'peer_lane_files_modified':False,'runtime_test_performed':False,'runtime_validation':'UNTESTED','automation_validation':'PENDING','validation_mode':'C_BATCH_GATE','build_performed':False,'n100_used':False,'local_clone_used':False,'google_drive_used':False,'google_drive_write_performed':False,'gpt_library_used':False,'uploaded_archive_used':True,'vr_ffb_dx_changes':False,
        'status':'PASS','asset_id':ASSET,'source_sha256':SOURCE_SHA,'candidate_dds_sha256':candidate_sha,'prompt_contract':'outrun-first-pass-edit-v2','prompt_sha256':sha(pb),'prompt_json_sha256':sha(pb),'prompt_hash_basis':'exact UTF-8 bytes of KOREAN_PNG_REVIEW/DDF0392A/generation_prompt.json','signed_slant_gate':'PASS','changed_pixels_outside_edit_mask':0,'changed_pixels_in_protected_mask':0,'introduced_alpha_outside_source_region':0,'alpha_changed_outside_edit_mask':0}
    REVIEW.joinpath('qa_report.json').write_text(json.dumps(qa,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    evidence=[
        'localization/graphics/role_A/20260930-A00221-P00117/A00221_P00117_INDEX222_V2_PRODUCTION.json',
        'localization/graphics/KOREAN_PNG_REVIEW/DDF0392A/source_display.png',
        'localization/graphics/KOREAN_PNG_REVIEW/DDF0392A/source_text_mask_display.png',
        'localization/graphics/KOREAN_PNG_REVIEW/DDF0392A/protected_mask_display.png',
        'localization/graphics/KOREAN_PNG_REVIEW/DDF0392A/clean_plate_display.png',
        'localization/graphics/KOREAN_PNG_REVIEW/DDF0392A/lettering_display.png',
        'localization/graphics/KOREAN_PNG_REVIEW/DDF0392A/candidate_display.png',
        'localization/graphics/KOREAN_PNG_REVIEW/DDF0392A/diff_display.png',
        'localization/graphics/KOREAN_PNG_REVIEW/DDF0392A/comparison.png',
        'localization/graphics/KOREAN_PNG_REVIEW/DDF0392A/element_comparison.png',
        'localization/graphics/KOREAN_PNG_REVIEW/DDF0392A/generation_prompt.json',
        'localization/graphics/KOREAN_PNG_REVIEW/DDF0392A/qa_report.json',
        'localization/graphics/hd_candidates/textures/load/spr_sprani_sumo_fe_cvt_Exst/DDF0392A_256x512.dds'
    ]
    material={'type':'INDEX222_DDF0392A_RENDER_READY_V2_KOREAN_DXT5_CANDIDATE_WITH_MANDATORY_REVIEW_SET','reviewed_indices':[222],'reviewed_assets':[ASSET],'candidate_dds_sha256':candidate_sha,'candidate_dds_modified':True,'translated_regions':6,'protected_original_regions':19,'changed_pixels_outside_allowed_edit_mask':0,'alpha_changed_pixels_outside_allowed_edit_mask':0,'changed_pixels_in_protected_regions':0,'one_pixel_overflow':0,'material_payload_in_result_commit':True,'durable_task_record_in_result_commit':True,'materially_reduces_unresolved_work':True}
    report={'schema_version':14,'schema':'outrun-a00221-index222-render-ready-v2-production-v1','task_id':TASK_ID,'wave_id':WAVE_ID,'lane':'LOCALIZATION_A','role':'CONTINUOUS_PRODUCTION_LANE_A_SELF_QA','target_branch':'korean-localization-clean','attempt':'1/3','recorded_at_kst':now,'base_head_sha':base,'result':'PASS_MATERIAL_A_MOD3_INDEX222_RENDER_READY_V2_KOREAN_DXT5_CANDIDATE_STATIC_SELF_QA_RUNTIME_UNTESTED','selection':{'shard_rule':'asset_queue.index % 3 == 0','selected_index':222,'asset':ASSET,'priority':'RENDER_READY_CANDIDATE_COMPLETION','accepted_c_gate':'C149/Q00047 authoritative 149ce00855248574d0813d34ba34da2a1e336f17 / run 36633937501','skipped_qa_pending_indices':[159,198,201,231]},'source_identity':qa['source'],'accepted_precandidate_lineage':qa['accepted_precandidate_lineage'],'render':qa['render'],'candidate':qa['candidate'],'visual_review_contract':qa['visual_review_contract'],'material_deliverable':material,'self_qa':'PASS_INDEX222_MOD3_EQ_0__C149_Q00047_RENDER_READY__EXACT_PINNED_ARCHIVE_AND_MEMBER__DXT5_1024X2048_MIP1__FLIP_Y__6_OF_6_KOREAN_SAFE_BBOX__NATIVE_FONT_NO_FLATTEN_RESIZE__SOURCE_SLANT_NONE_CANDIDATE_NONE__HEADER128_EXACT__BC3_TOUCHED_BLOCK_PATCH__ZERO_OUTSIDE_EDIT__ZERO_PROTECTED__MANDATORY_GITHUB_REVIEW_SET__RUNTIME_UNTESTED','candidate_static_qa':'PASS_PRODUCER_MACHINE_AND_VISUAL_PENDING_INDEPENDENT_C','candidate_dds_modified':True,'shared_state_modified':False,'peer_lane_files_modified':False,'runtime_test_performed':False,'runtime_validation':'UNTESTED','build_performed':False,'n100_used':False,'local_clone_used':False,'gpt_library_used_as_source_or_ssot':False,'google_drive_used':False,'google_drive_write_performed':False,'uploaded_archive_used':True,'work_stolen_from_lane':None,'vr_ffb_dx_changes':False,'automation_validation':'PENDING','validation_mode':'C_BATCH_GATE','evidence':evidence}
    REPORT.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    task={'schema_version':14,'task_id':TASK_ID,'wave_id':WAVE_ID,'lane':'LOCALIZATION_A','target_branch':'korean-localization-clean','attempt':'1/3','recorded_at_kst':now,'base_head_sha':base,'base_sha':base,'commit_mode':'GITHUB_ACTIONS_ATOMIC_LANE_LOCAL_INDEX222_V2_CANDIDATE_REVIEW_SET_AND_DURABLE_TASK_RECORD','result':'PASS_MATERIAL_A_MOD3_INDEX222_RENDER_READY_KOREAN_DXT5_CANDIDATE_STATIC_QA_RUNTIME_UNTESTED','summary':'Consumed authoritative C149/Q00047 RENDER_READY index222/DDF0392A without repeating accepted preflight. The exact pinned 1024x2048 DXT5 source reproduces all six accepted masks and CLEAN_PLATE, source baseline/slant is upright horizontal zero-slant, all six approved Korean strings are freshly rendered inside the final 2px-safe boxes using native Noto Sans CJK KR Bold with no flattened-raster resize, then FLIP_Y raw storage and exact 128-byte DDS header are preserved. Only changed BC3 blocks are patched; decoded-final self-QA reports zero changed/alpha pixels outside the allowed edit blocks, zero protected-region changes, and zero 1px overflow. Mandatory review PNGs are deterministic and match the exact candidate fingerprint already manually reviewed in this invocation. Runtime remains UNTESTED.','evidence':evidence,'material_deliverable':material,'readiness_audit':{'shard_rule':'asset_queue.index % 3 == 0','selected_priority':'RENDER_READY_CANDIDATE_COMPLETION','selected_indices':[222],'accepted_c_gate':'C149/Q00047 authoritative 149ce00855248574d0813d34ba34da2a1e336f17 / run 36633937501','qa_pending_not_repeated':{'159':'A00196 candidate','198':'A00208 candidate','201':'A00196 candidate','231':'A00218 preflight'},'readiness_before':{'222':'RENDER_READY'},'readiness_after':{'222':'CANDIDATE_PERSISTED_PRODUCER_STATIC_PASS_PENDING_INDEPENDENT_C'}},'self_qa':report['self_qa'],'candidate_static_qa':'PASS_PRODUCER_MACHINE_AND_VISUAL_PENDING_INDEPENDENT_C','candidate_dds_modified':True,'shared_state_modified':False,'peer_lane_files_modified':False,'runtime_test_performed':False,'runtime_validation':'UNTESTED','build_performed':False,'n100_used':False,'local_clone_used':False,'gpt_library_used_as_source_or_ssot':False,'google_drive_used':False,'google_drive_write_performed':False,'uploaded_archive_used':True,'work_stolen_from_lane':None,'vr_ffb_dx_changes':False,'automation_validation':'PENDING','validation_mode':'C_BATCH_GATE','result_sha':None,'authoritative_result_sha':None,'bookkeeping_note':'Immutable producer result commit atomically contains exact AUTO marker, candidate/review set, role_A report and durable task record. RESULT_SHA is filled only in a later bookkeeping commit. Producer automation_validation remains PENDING for C_BATCH_GATE; RUNTIME_VALIDATION=UNTESTED.'}
    TASK.parent.mkdir(parents=True,exist_ok=True); TASK.write_text(json.dumps(task,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(json.dumps({'status':'PASS','candidate_sha256':candidate_sha,'prompt_sha256':sha(pb),'changed_bc3_blocks':int(tbt.sum()),'changed_pixels':int(changed.sum()),'result_record':str(TASK.relative_to(ROOT))},ensure_ascii=False))
if __name__=='__main__': main()
