from pathlib import Path


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'missing expected block in {path}')
    path.write_text(text.replace(old, new, 1), encoding='utf-8')


build = Path('src/hooks_wheel_ffb_build.cpp')

old_latch = '''        if (mixedSurface)\n        {\n            const float minDistance =\n                std::abs(surface.minimum - SnowSurfaceBaseline);\n            const float maxDistance =\n                std::abs(surface.maximum - SnowSurfaceBaseline);\n            const float candidate = minDistance >= maxDistance\n                ? surface.minimum\n                : surface.maximum;\n\n            // Do not latch ordinary snow noise. This is deliberately tied to the\n            // same 0.08 spread that already qualified as a real mixed surface.\n            if (std::max(minDistance, maxDistance) >= 0.08f)\n            {\n                snowCurbLatched = true;\n                snowCurbMaterial = candidate;\n                snowCurbHoldUntil = now + SnowCurbHoldMs;\n            }\n        }\n\n        if (!snowCurbLatched)\n            return false;\n\n        const float uniformValue =\n            (surface.minimum + surface.maximum) * 0.5f;\n        const bool nearlyUniform = surface.spread < 0.08f;\n\n        // Returning to the normal ~0.50 snow surface must end the latch before\n        // testing whether the value still resembles the curb. A low-scalar curb\n        // around 0.40 used to match both tests and could extend forever on snow.\n        if (nearlyUniform &&\n            std::abs(uniformValue - SnowSurfaceBaseline) <= 0.05f)\n        {\n            clear_snow_curb_latch();\n            return false;\n        }\n\n        const float curbDistance =\n            std::abs(snowCurbMaterial - SnowSurfaceBaseline);\n        const float materialTolerance =\n            std::clamp(curbDistance * 0.35f, 0.025f, 0.06f);\n        const bool sameCurbMaterial = nearlyUniform &&\n            std::abs(uniformValue - snowCurbMaterial) <= materialTolerance;\n\n        if (sameCurbMaterial)\n        {\n            // Extend while all tyres remain on the identified curb/shoulder.\n            snowCurbHoldUntil = now + SnowCurbHoldMs;\n            return true;\n        }\n\n        // Signed subtraction remains correct across GetTickCount wrap.\n        if (snowCurbHoldUntil != 0 &&\n            static_cast<LONG>(now - snowCurbHoldUntil) < 0)\n            return true;\n\n        clear_snow_curb_latch();\n        return false;\n'''

new_latch = '''        // A snow-curb latch may only start from a transition that still contains\n        // the real ~0.50 snow baseline. This prevents post-stage asphalt values\n        // such as 0.25/0.35 from being reclassified as a new snow curb.\n        const bool minimumIsSnowBaseline =\n            std::abs(surface.minimum - SnowSurfaceBaseline) <= 0.06f;\n        const bool maximumIsSnowBaseline =\n            std::abs(surface.maximum - SnowSurfaceBaseline) <= 0.06f;\n        const bool mixedTouchesSnowBaseline =\n            mixedSurface && (minimumIsSnowBaseline || maximumIsSnowBaseline);\n\n        if (mixedTouchesSnowBaseline)\n        {\n            float candidate = surface.minimum;\n            if (minimumIsSnowBaseline && !maximumIsSnowBaseline)\n                candidate = surface.maximum;\n            else if (maximumIsSnowBaseline && !minimumIsSnowBaseline)\n                candidate = surface.minimum;\n            else\n            {\n                const float minDistance =\n                    std::abs(surface.minimum - SnowSurfaceBaseline);\n                const float maxDistance =\n                    std::abs(surface.maximum - SnowSurfaceBaseline);\n                candidate = minDistance >= maxDistance\n                    ? surface.minimum\n                    : surface.maximum;\n            }\n\n            // Only a meaningful departure from snow starts/re-arms the one-shot\n            // hold. The hold deadline is never extended by uniform curb contact.\n            if (std::abs(candidate - SnowSurfaceBaseline) >= 0.08f)\n            {\n                snowCurbLatched = true;\n                snowCurbMaterial = candidate;\n                snowCurbHoldUntil = now + SnowCurbHoldMs;\n            }\n        }\n\n        if (!snowCurbLatched)\n            return false;\n\n        const float uniformValue =\n            (surface.minimum + surface.maximum) * 0.5f;\n        const bool nearlyUniform = surface.spread < 0.08f;\n\n        // Returning to the normal ~0.50 snow surface ends the latch immediately.\n        if (nearlyUniform &&\n            std::abs(uniformValue - SnowSurfaceBaseline) <= 0.05f)\n        {\n            clear_snow_curb_latch();\n            return false;\n        }\n\n        // A completed curb crossing is retained only for the fixed 450 ms grace\n        // period that began at the last confirmed snow<->curb mixed contact.\n        // Uniform curb/road contact must never refresh this deadline.\n        if (snowCurbHoldUntil != 0 &&\n            static_cast<LONG>(now - snowCurbHoldUntil) < 0)\n            return true;\n\n        clear_snow_curb_latch();\n        return false;\n'''
replace_once(build, old_latch, new_latch)

old_surface = '''        const RoadSurfaceProfile surface = sample_surface_profile(car);\n        const bool mixedSurface =\n            surface.validSamples >= 2 && surface.spread >= 0.08f;\n        const bool genuinelyRough = surface.maximum >= 0.60f;\n        const bool fullyRough =\n            surface.validSamples >= 2 && surface.minimum >= 0.60f;\n        const DWORD now = GetTickCount();\n        const bool snowStage = is_snow_or_ice_stage_for_ffb();\n        const bool snowCurbHeld = update_snow_curb_latch(\n            surface, snowStage, mixedSurface, now);\n        const bool strongTactile = mixedSurface || fullyRough || snowCurbHeld;\n        const bool tactileSurface =\n            mixedSurface || genuinelyRough || snowCurbHeld;\n'''

new_surface = '''        const RoadSurfaceProfile surface = sample_surface_profile(car);\n        const bool rawMixedSurface =\n            surface.validSamples >= 2 && surface.spread >= 0.08f;\n        const bool genuinelyRough = surface.maximum >= 0.60f;\n        // Ordinary route-fork/asphalt material changes (for example 0.25/0.35)\n        // are not tactile curbs. A non-snow mixed transition must include a\n        // genuinely rough material before the compatibility boost is allowed.\n        const bool mixedSurface = rawMixedSurface && genuinelyRough;\n        const bool fullyRough =\n            surface.validSamples >= 2 && surface.minimum >= 0.60f;\n        const DWORD now = GetTickCount();\n        const bool snowStage = is_snow_or_ice_stage_for_ffb();\n        const bool snowCurbHeld = update_snow_curb_latch(\n            surface, snowStage, rawMixedSurface, now);\n        const bool strongTactile = mixedSurface || fullyRough || snowCurbHeld;\n        const bool tactileSurface = genuinelyRough || snowCurbHeld;\n'''
replace_once(build, old_surface, new_surface)

verify = Path('tools/verify_wheel_ffb_current.py')
text = verify.read_text(encoding='utf-8')
text = text.replace("runtime = read('src/wheel_ffb_runtime.hpp')\n", "runtime = read('src/wheel_ffb_runtime.hpp')\nbuild = read('src/hooks_wheel_ffb_build.cpp')\n", 1)
text = text.replace("    ('src/hooks_wheel_ffb.cpp', ffb),\n", "    ('src/hooks_wheel_ffb.cpp', ffb),\n    ('src/hooks_wheel_ffb_build.cpp', build),\n", 1)
append = '''\n\n# v01-snow-latch-route-fork-regression-guards\nreq(build, 'const bool mixedTouchesSnowBaseline =', 'snow curb latch starts only from a transition touching the snow baseline')\nreq(build, 'const bool mixedSurface = rawMixedSurface && genuinelyRough;', 'ordinary low-roughness route-fork material changes do not trigger tactile boost')\nreq(build, 'const bool tactileSurface = genuinelyRough || snowCurbHeld;', 'general tactile compatibility path requires real roughness or an active snow latch')\nif build.count('snowCurbHoldUntil = now + SnowCurbHoldMs;') != 1:\n    raise SystemExit('CURRENT VERIFY FAILED [snow curb hold deadline is re-armed outside confirmed mixed snow contact]')\nprint('OK [snow curb hold deadline has one confirmed-contact re-arm site]')\nforbid(build, 'Extend while all tyres remain on the identified curb/shoulder.', 'uniform curb contact cannot indefinitely refresh snow latch')\n'''
if '# v01-snow-latch-route-fork-regression-guards' not in text:
    text += append
verify.write_text(text, encoding='utf-8')

notes = Path('RELEASE_NOTES_v0.1.md')
text = notes.read_text(encoding='utf-8')
text = text.replace(
    'Road and snow/curb tactile feedback remain enabled. The snow-stage compensation is retained because it provides useful curb/shoulder feedback in physical testing.\n',
    'Road and snow/curb tactile feedback remain enabled. The snow-stage compensation is retained because it provides useful curb/shoulder feedback in physical testing. The v0.1 refresh also fixes a persistent-vibration bug after snow stages: the snow curb latch now expires after its fixed 450 ms grace period, and low-roughness route-fork material changes no longer trigger the curb boost.\n',
    1,
)
text = text.replace(
    '노면과 눈길 연석 진동은 유지했습니다. 눈 맵 보정은 실제 테스트에서 연석/숄더 감각을 어느 정도 살려주는 효과가 있어 v0.1에 그대로 포함합니다.\n',
    '노면과 눈길 연석 진동은 유지했습니다. 눈 맵 보정은 실제 테스트에서 연석/숄더 감각을 어느 정도 살려주는 효과가 있어 v0.1에 그대로 포함합니다. 이번 v0.1 갱신에서는 눈길 종료 후 진동이 계속되는 버그도 수정했습니다. 눈길 연석 latch는 확인된 mixed 접촉 후 450ms까지만 유지되며, 거칠기가 낮은 일반 갈림길 재질 변화는 연석 진동으로 증폭하지 않습니다.\n',
    1,
)
notes.write_text(text, encoding='utf-8')

print('snow latch / route fork v0.1 patch applied')
