from pathlib import Path


def replace_exact(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{path}: expected exactly one match, got {count}")
    p.write_text(text.replace(old, new, 1), encoding="utf-8")


stereo = "src/vr/d3d9/stereo_renderer_r13.cpp"
old_guard = '''        template <typename ActualDraw, typename LegacyDraw>\n        HRESULT R13GuardedDraw(IDirect3DDevice9* device,\n            ActualDraw&& actualDraw, LegacyDraw&& legacyDraw, const char* site)\n        {\n            if (!IsGameDevice(device) || InternalStereoPass)\n                return legacyDraw();\n\n            const bool mainTarget = TargetIsBackBuffer();\n            if (R13ForceMonoShadow && mainTarget)\n                return R13DrawMonoShadowOnce(device, actualDraw, site);\n\n            const bool unsafeMrt = mainTarget && AnyAuxRenderTargetActive();\n            const bool unsafeOcclusion = mainTarget &&\n                (ActiveOcclusionQueries.load(std::memory_order_acquire) > 0 ||\n                 OcclusionQueryTrackingUnavailable.load(std::memory_order_acquire));\n            if (StereoWanted() && R9StereoSeeded &&\n                (unsafeMrt || unsafeOcclusion))\n            {\n                const auto reason = unsafeMrt\n                    ? OutRunVR::StereoFailureMrtActive\n                    : OutRunVR::StereoFailureOcclusionQueryActive;\n                R9Poison(reason, site);\n                ++R13UnsafeTransitionFrames;\n\n                if (R9MonoSeeded && !R9MonoBackupGap &&\n                    R9CurrentDepthCanMirror())\n                {\n                    R13ForceMonoShadow = true;\n                    if (!R13FirstUnsafeTransitionLogged)\n                    {\n                        R13FirstUnsafeTransitionLogged = true;\n                        spdlog::info(\n                            "VR R13 review hardening: unsafe MRT/occlusion transition switches the remainder of the Present to single-execution mono shadow; no duplicate query/MRT side effects");\n                    }\n                    return R13DrawMonoShadowOnce(device, actualDraw, site);\n                }\n\n                // If the independent mono history is unavailable, do not replay\n                // a side-effecting draw. Continue the real target once and mark\n                // the shadow unusable for Present restoration.\n                R9MonoBackupGap = true;\n                return actualDraw();\n            }\n\n            return legacyDraw();\n        }\n'''
new_guard = '''        template <typename ActualDraw, typename LegacyDraw>\n        HRESULT R13GuardedDraw(IDirect3DDevice9* device,\n            ActualDraw&& actualDraw, LegacyDraw&& legacyDraw, const char* site)\n        {\n            const bool gameDevice = IsGameDevice(device);\n            const bool internalStereo = InternalStereoPass;\n            if (!gameDevice || internalStereo)\n                return legacyDraw();\n\n            const bool mainTarget = TargetIsBackBuffer();\n            if (!mainTarget)\n                return legacyDraw();\n\n            const bool unsafeMrt = AnyAuxRenderTargetActive();\n            const bool unsafeOcclusion =\n                ActiveOcclusionQueries.load(std::memory_order_acquire) > 0 ||\n                OcclusionQueryTrackingUnavailable.load(std::memory_order_acquire);\n            const bool stereoWanted = StereoWanted();\n            const auto replayPolicy = OutRunVR::PassPolicy::ClassifyDrawReplay(\n                gameDevice, internalStereo, mainTarget, R13ForceMonoShadow,\n                stereoWanted, R9StereoSeeded, unsafeMrt, unsafeOcclusion);\n\n            if (replayPolicy == OutRunVR::PassPolicy::DrawReplayPolicy::Legacy)\n                return legacyDraw();\n            if (replayPolicy == OutRunVR::PassPolicy::DrawReplayPolicy::ForcedMonoShadow)\n                return R13DrawMonoShadowOnce(device, actualDraw, site);\n\n            // UnsafeSingleExecution is the fail-closed class: MRT/query side\n            // effects must execute only once even if stereo had already begun.\n            const auto reason = unsafeMrt\n                ? OutRunVR::StereoFailureMrtActive\n                : OutRunVR::StereoFailureOcclusionQueryActive;\n            R9Poison(reason, site);\n            ++R13UnsafeTransitionFrames;\n\n            if (R9MonoSeeded && !R9MonoBackupGap &&\n                R9CurrentDepthCanMirror())\n            {\n                R13ForceMonoShadow = true;\n                if (!R13FirstUnsafeTransitionLogged)\n                {\n                    R13FirstUnsafeTransitionLogged = true;\n                    spdlog::info(\n                        "VR R13 pass policy: unsafe MRT/occlusion classified single-execution; remainder of Present uses mono shadow without duplicated side effects");\n                }\n                return R13DrawMonoShadowOnce(device, actualDraw, site);\n            }\n\n            // If the independent mono history is unavailable, do not replay a\n            // side-effecting draw. Continue the real target once and mark the\n            // shadow unusable for Present restoration.\n            R9MonoBackupGap = true;\n            return actualDraw();\n        }\n'''
replace_exact(stereo, old_guard, new_guard)

old_tail = '''    bool IsMainBackbufferPoseInjectionPass() noexcept\n    {\n        return TargetIsBackBuffer() && !AnyAuxRenderTargetActive() &&\n            !InternalStereoPass;\n    }\n}\n'''
new_tail = '''    OutRunVR::PassPolicy::PoseInjectionPolicy CurrentPoseInjectionPolicy() noexcept\n    {\n        return OutRunVR::PassPolicy::ClassifyPoseInjection(\n            InternalStereoPass, TargetIsBackBuffer(), AnyAuxRenderTargetActive());\n    }\n\n    bool IsMainBackbufferPoseInjectionPass() noexcept\n    {\n        return OutRunVR::PassPolicy::AllowsPoseInjection(\n            CurrentPoseInjectionPolicy());\n    }\n}\n'''
replace_exact(stereo, old_tail, new_tail)

renderer = "src/vr/game/outrun_renderer_r13.cpp"
old_condition = '''                UploadTouchesOutRunWvp(startRegister, vector4fCount) &&\n                !OutRunVRStereo::IsMainBackbufferPoseInjectionPass())\n'''
new_condition = '''                UploadTouchesOutRunWvp(startRegister, vector4fCount) &&\n                !OutRunVR::PassPolicy::AllowsPoseInjection(\n                    OutRunVRStereo::CurrentPoseInjectionPolicy()))\n'''
replace_exact(renderer, old_condition, new_condition)

old_log = '''                        "VR R13: auxiliary/offscreen c64 WVP kept stock; HMD transform is now main-backbuffer-only");\n'''
new_log = '''                        "VR R13 pass policy: auxiliary/offscreen c64 WVP kept stock; HMD transform is main-backbuffer-only");\n'''
replace_exact(renderer, old_log, new_log)

print("VR pass policy applied successfully")
