from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "src/hooks_wheel_ffb.cpp"
VERIFIER = ROOT / "tools/verify_wheel_ffb_current.py"
CRLF = b"\r\n"


def patch_bytes(data: bytes, old: bytes, new: bytes, label: str) -> bytes:
    old = old.replace(b"\n", CRLF)
    new = new.replace(b"\n", CRLF)
    count = data.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly one match, got {count}")
    print(f"patched: {label}")
    return data.replace(old, new, 1)


data = SOURCE.read_bytes()

data = patch_bytes(data, b'''                if (!ready)\n                {\n                    retryAfter_ = GetTickCount() + FFB_DEVICE_FAILED_BACKOFF_MS;\n                    return;\n                }''', b'''                if (!ready)\n                {\n                    // initialize() can request the short retry interval for\n                    // transient startup/focus conditions. Do not overwrite that\n                    // with the rejected-interface backoff.\n                    const DWORD retryNow = GetTickCount();\n                    if (!tick_before(retryNow, retryAfter_))\n                        retryAfter_ = retryNow + FFB_DEVICE_FAILED_BACKOFF_MS;\n                    return;\n                }''', "preserve transient short retry")

data = patch_bytes(data, b'''            const bool hadInitializedOutput = initialized_;\n            if (initialized_)\n            {\n                if (device_ && deviceAcquired_)\n                    zero_all_forces();\n                teardown_for_reinitialize("live disable");\n                initialized_ = false;\n                deviceReinitPending_ = false;\n                deviceFailureSince_ = 0;\n                deviceReinitAfter_ = 0;\n                retryAfter_ = 0;\n                failedInterfaces_.clear();\n                preferredVidPid_ = 0;\n            }\n\n            enabledLastTick_ = false;''', b'''            const bool hadInitializedOutput = initialized_;\n            if (initialized_)\n            {\n                if (device_ && deviceAcquired_)\n                    zero_all_forces();\n                teardown_for_reinitialize("live disable");\n                initialized_ = false;\n            }\n\n            // Disabling FFB is a hard recovery boundary even if initialization\n            // never completed. A previous rejected-interface quarantine must not\n            // survive a deliberate off/on cycle or a fresh device selection.\n            deviceReinitPending_ = false;\n            deviceFailureSince_ = 0;\n            deviceReinitAfter_ = 0;\n            retryAfter_ = 0;\n            failedInterfaces_.clear();\n            preferredVidPid_ = 0;\n\n            enabledLastTick_ = false;''', "hard reset failed-interface state on disable")

data = patch_bytes(data, b'''            gameHwnd_ = Game::GameHwnd();\n            if (!gameHwnd_)\n            {\n                spdlog::error("WheelFFB: game window not available yet");\n                release_device();\n                release_directinput();\n                return false;\n            }''', b'''            gameHwnd_ = Game::GameHwnd();\n            if (!gameHwnd_)\n            {\n                spdlog::warn("WheelFFB: game window not available yet; retrying shortly");\n                release_device();\n                release_directinput();\n                retryAfter_ = GetTickCount() + FFB_DEVICE_RETRY_MS;\n                return false;\n            }''', "short retry while game window is unavailable")

data = patch_bytes(data, b'''            if (hr == DIERR_INPUTLOST || hr == DIERR_NOTACQUIRED)\n            {\n                if (reacquire_after_input_loss("GUID_Spring", hr))\n                    hr = springEffect_->SetParameters(\n                        &params, DIEP_TYPESPECIFICPARAMS | DIEP_START);\n            }''', b'''            if (hr == DIERR_INPUTLOST || hr == DIERR_NOTACQUIRED)\n            {\n                if (!reacquire_after_input_loss("GUID_Spring", hr))\n                    return;\n                hr = springEffect_->SetParameters(\n                    &params, DIEP_TYPESPECIFICPARAMS | DIEP_START);\n                if (hr == DIERR_INPUTLOST || hr == DIERR_NOTACQUIRED)\n                {\n                    note_device_failure("GUID_Spring retry", hr);\n                    return;\n                }\n            }''', "preserve Spring transient-loss grace")

data = patch_bytes(data, b'''            if (hr == DIERR_INPUTLOST || hr == DIERR_NOTACQUIRED)\n            {\n                if (reacquire_after_input_loss("GUID_Damper", hr))\n                    hr = damperEffect_->SetParameters(\n                        &params, DIEP_TYPESPECIFICPARAMS | DIEP_START);\n            }''', b'''            if (hr == DIERR_INPUTLOST || hr == DIERR_NOTACQUIRED)\n            {\n                if (!reacquire_after_input_loss("GUID_Damper", hr))\n                    return;\n                hr = damperEffect_->SetParameters(\n                    &params, DIEP_TYPESPECIFICPARAMS | DIEP_START);\n                if (hr == DIERR_INPUTLOST || hr == DIERR_NOTACQUIRED)\n                {\n                    note_device_failure("GUID_Damper retry", hr);\n                    return;\n                }\n            }''', "preserve Damper transient-loss grace")

data = patch_bytes(data, b'''            if (hr == DIERR_INPUTLOST || hr == DIERR_NOTACQUIRED)\n            {\n                if (reacquire_after_input_loss("GUID_Sine periodic", hr))\n                    hr = effect->SetParameters(\n                        &params, DIEP_TYPESPECIFICPARAMS | DIEP_START);\n            }''', b'''            if (hr == DIERR_INPUTLOST || hr == DIERR_NOTACQUIRED)\n            {\n                if (!reacquire_after_input_loss("GUID_Sine periodic", hr))\n                    return;\n                hr = effect->SetParameters(\n                    &params, DIEP_TYPESPECIFICPARAMS | DIEP_START);\n                if (hr == DIERR_INPUTLOST || hr == DIERR_NOTACQUIRED)\n                {\n                    note_device_failure("GUID_Sine periodic retry", hr);\n                    return;\n                }\n            }''', "preserve Periodic transient-loss grace")

data = patch_bytes(data, b'''            if (hr == DIERR_INPUTLOST || hr == DIERR_NOTACQUIRED)\n            {\n                if (reacquire_after_input_loss("ConstantForce", hr) && constantEffect_)\n                    hr = constantEffect_->SetParameters(&params, flags);\n            }''', b'''            if (hr == DIERR_INPUTLOST || hr == DIERR_NOTACQUIRED)\n            {\n                // Input loss is a transient ownership/focus condition, not proof\n                // that this physical DirectInput interface is the wrong FFB port.\n                // Preserve the grace window before any device reinitialization.\n                if (!reacquire_after_input_loss("ConstantForce", hr) || !constantEffect_)\n                    return;\n                hr = constantEffect_->SetParameters(&params, flags);\n                if (hr == DIERR_INPUTLOST || hr == DIERR_NOTACQUIRED)\n                {\n                    note_device_failure("ConstantForce retry", hr);\n                    return;\n                }\n            }''', "do not quarantine transient ConstantForce input loss")

SOURCE.write_bytes(data)

verify = VERIFIER.read_bytes()
anchor = b'''req(ffb, 'mark_selected_interface_failed("ConstantForce live SetParameters", hr)', 'runtime ConstantForce failure quarantines the bad interface before reinit')\r\n'''
extra = anchor + b'''req(ffb, 'if (!tick_before(retryNow, retryAfter_))', 'transient short retry is not overwritten by rejected-interface backoff')\r\nreq(ffb, 'previous rejected-interface quarantine must not', 'FFB disable hard-resets failed-interface recovery state')\r\nreq(ffb, 'if (!reacquire_after_input_loss("ConstantForce", hr) || !constantEffect_)', 'ConstantForce transient input loss keeps the recovery grace window')\r\nreq(ffb, 'if (!reacquire_after_input_loss("GUID_Spring", hr))', 'Spring transient input loss keeps the recovery grace window')\r\nreq(ffb, 'if (!reacquire_after_input_loss("GUID_Damper", hr))', 'Damper transient input loss keeps the recovery grace window')\r\nreq(ffb, 'if (!reacquire_after_input_loss("GUID_Sine periodic", hr))', 'Periodic transient input loss keeps the recovery grace window')\r\nreq(ffb, 'game window not available yet; retrying shortly', 'missing game window uses the short device retry')\r\n'''
if verify.count(anchor) != 1:
    raise SystemExit(f"verifier anchor: expected exactly one match, got {verify.count(anchor)}")
VERIFIER.write_bytes(verify.replace(anchor, extra, 1))
print("FFB recovery hardening applied")
