from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent

def read(rel):
    p = ROOT / rel
    if not p.exists():
        raise SystemExit(f'CURRENT VERIFY FAILED [missing file]: {rel}')
    return p.read_text(encoding='utf-8')

def req(text, needle, label):
    if needle not in text:
        raise SystemExit(f'CURRENT VERIFY FAILED [{label}]: {needle!r}')
    print(f'OK [{label}]')

def forbid(text, needle, label):
    if needle in text:
        raise SystemExit(f'CURRENT VERIFY FAILED [{label}]: forbidden {needle!r}')
    print(f'OK [{label}]')

ffb = read('src/hooks_wheel_ffb.cpp')
vib = read('src/hooks_forcefeedback.cpp')
dyn = read('src/hooks_wheel_vehicle_dynamics.hpp')
math = read('src/wheel_ffb_math.hpp')
ps2 = read('src/wheel_ffb_ps2.hpp')
input_cpp = read('src/input_manager.cpp')
input_hpp = read('src/input_manager.hpp')
bind_ui = read('src/overlay/input_bindings_ui.cpp')
wheel_ui = read('src/overlay/wheel_setup_ui.cpp')
profiles = read('src/wheel_profile_store.hpp')
runtime = read('src/wheel_ffb_runtime.hpp')
build = read('src/hooks_wheel_ffb_build.cpp')
ini = read('OutRun2006Tweaks.ini')
workflow = read('.github/workflows/build.yml')

if (ROOT / 'src/hooks_wheel_physics_sat.hpp').exists():
    raise SystemExit('CURRENT VERIFY FAILED [obsolete Physics SAT helper still active]')

for rel, text in [
    ('src/hooks_wheel_ffb.cpp', ffb),
    ('src/hooks_wheel_ffb_build.cpp', build),
    ('src/hooks_forcefeedback.cpp', vib),
    ('src/hooks_wheel_vehicle_dynamics.hpp', dyn),
    ('src/wheel_ffb_ps2.hpp', ps2),
    ('src/input_manager.cpp', input_cpp),
    ('src/overlay/input_bindings_ui.cpp', bind_ui),
    ('src/overlay/wheel_setup_ui.cpp', wheel_ui),
    ('src/wheel_profile_store.hpp', profiles),
]:
    if '\x00' in text:
        raise SystemExit(f'CURRENT VERIFY FAILED [NUL byte in source]: {rel}')
    if text.count('{') != text.count('}'):
        raise SystemExit(f'CURRENT VERIFY FAILED [brace balance]: {rel}')
    print(f'OK [brace balance {rel}]')

req(ini, 'UseNewInput = true', 'shipped SDL multi-device input default')
for rel in (
    'src/wheel_profile_store.hpp', 'src/hooks_input.cpp',
    'src/overlay/settings_ui.cpp', 'src/overlay/overlay.cpp',
    'src/wheel_ffb_ps2.hpp',
    'CMakeLists.txt', 'cmake.toml', 'README.md', 'WHEEL_FFB.md',
    'RELEASE_NOTES_v0.1.md', '.github/workflows/build.yml',
):
    req(workflow, rel, f'source snapshot includes verifier dependency {rel}')
req(input_cpp, 'float InputManager_SteeringValue()', 'InputManager steering bridge exported')
req(ffb, 'const float steering = InputManager_SteeringValue();', 'SAT reads active InputManager steering')
req(input_cpp, 'SDL_GetJoysticks', 'SDL raw joystick enumeration')
req(bind_ui, 'Input Bindings', 'single input-binding UI')
req(wheel_ui, 'Force Feedback', 'dedicated FFB UI')
req(wheel_ui, 'Legacy Wheel Setup', 'legacy input kept behind compatibility mode')
req(wheel_ui, 'draw_device_combo("FFB Output", true', 'FFB selector filters to FFB-capable interfaces')
req(wheel_ui, 'autoMatchedFfbGuid', 'FFB selector mirrors DeviceName substring auto-match before GUID save')
req(wheel_ui, 'draw_device_combo("Legacy Input Wheel", false', 'legacy input identity selected separately')
req(input_hpp, 'Path is only a duplicate-device tie-breaker/fallback', 'USB path is not hard binding identity')
compat_v2 = read('src/hooks_wheel_input_compat_v2.hpp')
r3_dpad = read('src/hooks_wheel_r3_menu_dpad.hpp')
r3_ab = read('src/hooks_wheel_r3_menu_ab.hpp')
req(compat_v2, 'return Settings::WheelInputCompatibility && !Settings::UseNewInput;', 'legacy V2 installed for live universal switching')
req(wheel_ui, 'bool validate() override { return Settings::WheelInputCompatibility && !Settings::UseNewInput; }', 'universal legacy hook installed for live switching')
req(r3_dpad, '!Settings::UseNewInput &&\n                Settings::WheelMenuR3DirectDPad;', 'R3 DPad hook can remain dormant under universal ownership')
req(r3_ab, '!Settings::UseNewInput &&\n                Settings::WheelMenuR3DirectAB;', 'R3 AB hook can remain dormant under universal ownership')
forbid(wheel_ui, 'Settings::WheelMenuR3DirectDPad = false;', 'universal toggle preserves R3 DPad preference')
forbid(wheel_ui, 'Settings::WheelMenuR3DirectAB = false;', 'universal toggle preserves R3 AB preference')
forbid(wheel_ui, 'Restart after changing the physical wheel base', 'FFB selector does not demand unnecessary restart')

req(ffb, 'GUID_ConstantForce', 'DirectInput ConstantForce effect')
req(ffb, '#include "Proxy.hpp"', 'FFB backend can access original proxy module')
req(ffb, 'GetProcAddress(proxy::origModule, "DirectInput8Create")', 'FFB backend uses original Windows DirectInput export')
forbid(ffb, 'createDirectInput = &::DirectInput8Create;', 'FFB backend never falls back through its own dinput8 proxy export')
req(ffb, 'std::vector<FailedInterfaceState> failedInterfaces_;', 'FFB backend can quarantine multiple rejected interfaces')
req(ffb, 'active_failed_interface_count()', 'FFB backend walks all rejected candidates instead of only one sibling')
req(ffb, 'const bool ready = initialize();', 'FFB candidate probing performs one potentially expensive interface open per update tick')
req(ffb, 'next compatible interface will be probed on the next update tick', 'rejected sibling probing yields back to the game thread')
forbid(ffb, 'while (!ready)', 'FFB candidate probing never loops over multiple device opens in one frame')
forbid(ffb, 'MaxInterfaceProbes', 'FFB candidate probing has no arbitrary interface-count ceiling')
req(ffb, 'DIPROP_VIDPID', 'FFB sibling selection can prefer matching physical VID/PID')
req(ffb, 'requirePreferredProductGuid', 'FFB sibling selection prefers the DirectInput product GUID for one physical device')
req(ffb, 'instance->guidFFDriver', 'FFB sibling selection can use the force-feedback driver identity')
req(ffb, 'requirePreferredDriverVendor', 'FFB sibling selection can fall back to same FFB driver plus USB vendor')
req(ffb, 'requirePreferredVidPid', 'FFB sibling selection has a same-VID/PID pass before name fallback')
req(ffb, 'DWORD axes[2] = { DIJOFS_X, DIJOFS_Y };', 'ConstantForce tries canonical X/Y polar descriptor independent of actuator count')
req(ffb, 'detected actuator one-axis CARTESIAN descriptor', 'ConstantForce can fall back to the actual enumerated actuator axis')
req(ffb, 'for (const DWORD detectedAxis : actuatorAxes_)', 'ConstantForce probes every enumerated actuator axis after canonical X')
forbid(ffb, 'actuatorAxes_.size() < 2', 'FFB actuator enumeration is not arbitrarily capped at two objects')
req(ffb, 'zero-force live SetParameters probe', 'ConstantForce candidate must validate the live update path at zero torque')
req(ffb, 'mark_selected_interface_failed("ConstantForce live SetParameters", hr)', 'runtime ConstantForce failure quarantines the bad interface before reinit')
req(ffb, 'FFB_CONSTANT_LIVE_FAILURE_LIMIT = 3', 'runtime ConstantForce quarantine requires repeated live-output failure')
req(ffb, 'if (!record_constant_live_failure())', 'single ConstantForce live-output failure is retained as transient')
req(ffb, 'transient ConstantForce update failure', 'transient ConstantForce failures are logged without immediate interface blacklist')
req(ffb, 'if (!tick_before(retryNow, retryAfter_))', 'transient short retry is not overwritten by rejected-interface backoff')
req(ffb, 'previous rejected-interface quarantine must not', 'FFB disable hard-resets failed-interface recovery state')
req(ffb, 'if (!reacquire_after_input_loss("ConstantForce", hr) || !constantEffect_)', 'ConstantForce transient input loss keeps the recovery grace window')
req(ffb, 'if (!reacquire_after_input_loss("GUID_Spring", hr))', 'Spring transient input loss keeps the recovery grace window')
req(ffb, 'if (!reacquire_after_input_loss("GUID_Damper", hr))', 'Damper transient input loss keeps the recovery grace window')
req(ffb, 'if (!reacquire_after_input_loss(effectName, hr))', 'Periodic transient input loss keeps the recovery grace window')
req(ffb, 'game window not available yet; retrying shortly', 'missing game window uses the short device retry')
req(ffb, 'Settings::write(Module::UserIniPath)', 'auto-selected working FFB GUID is persisted for the next launch')
req(ffb, 'saved FFB GUID unavailable or rejected; probing compatible sibling interfaces', 'saved FFB GUID can fall back to sibling interface')
req(ffb, 'FFB_DEVICE_FAILED_BACKOFF_MS = 10000', 'failed FFB interface retry is throttled')
req(ffb, 'device_->SendForceFeedbackCommand(DISFFC_RESET)', 'FFB interface reset before actuator enable')
req(ffb, 'GUID_Spring', 'DirectInput Spring effect')
req(ffb, 'GUID_Damper', 'DirectInput Damper effect')
req(ffb, 'WheelFFB_UpdateAfterPhysics(EVWORK_CAR* car)', 'post-physics FFB entry point')
forbid(ffb, 'CalcVibrationHook_', 'no competing CalcVibrationValues FFB hook')
req(vib, 'if (WheelFFB_IsOutputOwnerActive())', 'rumble suppression follows actual FFB ownership')
req(ffb, 'bool WheelFFB_IsOutputOwnerActive()', 'FFB ownership query exported')
req(ffb, 'deviceAcquired_ && !deviceReinitPending_ && !panicStopped_', 'FFB ownership requires acquired healthy output')
req(ffb, 'teardown_for_reinitialize("live disable")', 'live FFB disable fully releases output')
req(ffb, 'setting->hidden(true);', 'generic WheelFFB settings hidden')
req(vib, 'GamePlCar_Ctrl.call(car);\n        WheelFFB_UpdateAfterPhysics(car);', 'post-physics execution order')

calc = vib.find('CalcVibrationValues(car);')
ctrl = vib.find('GamePlCar_Ctrl.call(car);')
wheel = vib.find('WheelFFB_UpdateAfterPhysics(car);')
if not (0 <= calc < ctrl < wheel):
    raise SystemExit('CURRENT VERIFY FAILED [vibration/physics/FFB ordering]')
print('OK [vibration before physics; wheel FFB after physics]')

# Vehicle dynamics is now estimation-only; the main FFB engine owns force shaping.
req(ffb, '#include "hooks_wheel_vehicle_dynamics.hpp"', 'vehicle dynamics helper included')
req(dyn, 'class WheelVehicleDynamics', 'estimator separated from FFB torque')
forbid(dyn, 'satStrength', 'estimator owns no SAT strength')
forbid(dyn, 'gripLoss', 'estimator owns no grip tuning')
forbid(dyn, 'trailShape', 'estimator owns no tire-force curve')
req(dyn, 'roadWheelAngle - bodySlip_ - yawRate_ * yawLeadSeconds', 'front-slip proxy')
req(dyn, 'constexpr int CalibrationSamplesRequired = 12;', 'multi-sample basis calibration')
req(dyn, 'bestScore >= 0.85f && calibrationConfidence_ >= 0.25f', 'basis confidence gate')
req(dyn, 'motionScale > motionScaleEma_ * 5.0f', 'restart/warp discontinuity guard')
req(dyn, 'if (speedNorm <= 0.04f)', 'stopped-car dynamic state reset')
req(dyn, 'headingDelta * 60.0f', 'fixed 60 Hz yaw-rate derivative')
req(dyn, 'car->spd_mb_20.x', 'spd_mb telemetry retained')
req(dyn, 'if (invalidTicks_ > 4)\n            clear_dynamic_state();', 'stale dynamics cleared after invalid telemetry')

# field_264/268 are lateral load only. Slip/grip must come from dynamics.
req(ffb, 'const float lateralSum = car->field_264 + car->field_268;', 'OutRun lateral-G source retained')
req(ffb, 'const float lateralLoad = std::clamp(std::abs(latNorm), 0.0f, 1.0f);', 'lateral signal used as load magnitude')
req(ffb, 'vehicleDynamics_.update(car, steer, speedNorm, lateralLoadSmooth);', 'dynamics updated independently')
forbid(ffb, 'driftAmt', 'lateral-G drift detector removed')
forbid(ffb, 'gripFactor', 'shared lateral-G grip factor removed')
req(ffb, 'const float bodySlideT = std::clamp(', 'body slip drives chassis slide')
req(ffb, 'const float frontScrubT = std::clamp(', 'front slip drives tire scrub')
req(ffb, 'const float configuredSpringStrength = std::clamp(', 'spring strength is finite/bounded independently of grip/slip')
req(ffb, 'configuredSpringStrength * springSpeed', 'Modern/Arcade spring remains independent of grip/slip')
req(ffb, 'const float damperSlipRelief = std::max(bodySlide, frontScrub * 0.75f);', 'damper reveals front scrub and chassis slide')
req(ffb, 'const float damperRelease = 1.0f - 0.55f * gripLoss * damperSlipRelief;', 'damper release uses real slip state')
req(ffb, 'frontScrub * (0.50f + 0.50f * lateralLoadSmooth) +\n                    bodySlide * 0.20f', 'tire slip driven mainly by front scrub')
req(ffb, 'const float naturalSlideRelief =\n                1.0f - 0.25f * gripLoss * bodySlide;', 'Natural SAT unloads from real slide')
req(ffb, 'const float rearSlideRelief = 1.0f - 0.15f * gripLoss * bodySlide;', 'Physics SAT avoids body-slip double unload')
req(ffb, 'WheelFFBMath::pneumatic_sat_shape(frontSlip, trailResponseSlip)', 'production pneumatic SAT curve separates force and trail transients')
req(ffb, 'WheelFFBMath::combined_sat_shape(\n                frontSlip, trailResponseSlip, mechanicalTrailMix)', 'Physics SAT combines pneumatic and mechanical total trail')
req(ffb, '(frontSlip > 0.0f ? -1.0f : 1.0f)', 'Physics SAT direction follows front slip')
forbid(ffb, 'physicsGrip', 'old strong body-slip SAT double-unload removed')

req(wheel_ui, 'Physics SAT (body slip + yaw)', 'versionless Physics SAT UI')
req(wheel_ui, 'Load MOZA R3 Physics SAT', 'versionless Physics SAT preset')
req(wheel_ui, 'Grip-loss Response', 'grip-loss UI reflects broader role')
req(wheel_ui, 'Test Left (20%)', 'safe left test')
req(wheel_ui, 'Test Right (20%)', 'safe right test')
req(ffb, 'DI_FFNOMINALMAX', 'nominal DirectInput device gain')
req(ffb, 'WheelFFB: scheduling DirectInput device reinitialization', 'device recovery path')
req(ffb, 'SnowIceRoadTextureScale = 0.04f', 'snow/ice periodic attenuation')
req(ffb, 'std::isfinite', 'non-finite input/output guards')
req(wheel_ui, 'Settings::WheelFFBInvertForce = true;', 'R3 ConstantForce direction baseline')
req(wheel_ui, 'Settings::WheelFFBInvertSpring = false;', 'R3 Spring direction baseline')
req(wheel_ui, 'Settings::VibrationMode = 0;', 'R3 preset disables gamepad rumble')
req(ffb, 'load={:.2f} slide={:.2f} scrub={:.2f}', 'separated load/slide/scrub diagnostics')
req(ffb, 'step={:.5f} spdLen={:.5f} spdCorr={:.2f}', 'velocity diagnostic telemetry')
req(ffb, 'extern float VibrationLeftMotor;', 'original Xbox vibration witness left channel')
req(ffb, 'extern float VibrationRightMotor;', 'original Xbox vibration witness right channel')
req(ffb, 'origXboxL={:.3f} origXboxR={:.3f}', 'compact diagnostics expose original Xbox vibration witness')
req(ffb, 'xboxLeft={} xboxRight={}', '10 Hz telemetry exposes original Xbox vibration witness')
req(ffb, 'NOT left/right steering', 'witness channels are explicitly non-directional')
req(read('docs/reverse/LINDBERGH_FFB_MAP.md'), '0x08105A48', 'Lindbergh FFB comparative map retained')

for pattern, label in [
    (r'(?m)^SteeringDeadZone\s*=\s*0\.0\s*$', 'zero steering deadzone'),
    (r'(?m)^WheelAccelerationInvert\s*=\s*false\s*$', 'accelerator normal polarity'),
    (r'(?m)^WheelBrakeInvert\s*=\s*false\s*$', 'brake normal polarity'),
]:
    if not re.search(pattern, ini):
        raise SystemExit(f'CURRENT VERIFY FAILED [{label}]')
    print(f'OK [{label}]')

# These are structural guards, not a substitute for the compiled numeric tests.
cmake = read('CMakeLists.txt')
toml = read('cmake.toml')
for text in (cmake, toml):
    req(text, 'set_source_files_properties(src/hooks_wheel_ffb.cpp PROPERTIES HEADER_FILE_ONLY TRUE)', 'shim implementation is not a second TU')
for path in ('CMakeLists.txt', 'cmake.toml', '.github/workflows/build.yml'):
    forbid(read(path), 'tools/archive/rounds/', 'archive outside build graph')
    forbid(read(path), 'patch_wheel_round', 'no round patch invocation')
forbid(bind_ui, 'draw_force_feedback', 'no dead alternate FFB page')
forbid(ffb, 'WheelFFBLowSpeedSpring', 'unused low-speed setting removed')
forbid(ffb, 'WheelFFBSpringLoadBoost', 'unused load setting removed')
forbid(ffb, 'effect.dwDuration = INFINITE', 'effects have driver-side leases')
req(ffb, 'FFB_EFFECT_LEASE_US = 250000', '250ms driver lease')
req(ffb, 'FFB_EFFECT_REFRESH_MS = 100', '100ms lease renewal')
req(ffb, 'params.dwFlags = DIEFF_POLAR | DIEFF_OBJECTOFFSETS', 'explicit polar update descriptor')
req(read('src/hooks_framerate.cpp'), 'WheelFFB_ServiceSafety();', 'safety is serviced outside player-car callback')
req(wheel_ui, 'Save Force Feedback', 'dedicated FFB save action')
req(profiles, 'OutRun2006Tweaks.profiles', 'named wheel/FFB profile root')
req(profiles, 'Kind::Input ? "Input" : "FFB"', 'separate input and FFB profile folders')
req(profiles, 'InputBackend = ', 'wheel profile stores backend choice')
req(profiles, 'SteeringDeadZone = ', 'wheel profile stores steering deadzone')
req(profiles, 'BypassGameSensitivity = ', 'wheel profile stores sensitivity bypass')
req(profiles, 'FFBDeviceName = ', 'wheel profile stores FFB output name')
req(profiles, 'FFBDeviceGuid = ', 'wheel profile stores exact FFB output GUID')
forbid(profiles, 'UseNewInput = ', 'wheel profile never switches the input architecture live')
req(profiles, 'key != "DeviceName" && key != "DeviceGuid"', 'FFB profiles never reroute the output device')
req(profiles, 'key != "Telemetry" && key != "DebugLog"', 'FFB profiles keep diagnostics global')
req(profiles, 'load_ffb_profile(', 'transactional named FFB profile loader')
req(bind_ui, 'ImGui::BeginTabItem("Profiles")', 'input binding UI exposes wheel profiles')
req(bind_ui, 'WheelProfileStore::append_input_options', 'wheel profile saves wheel-specific input options')
req(bind_ui, 'manager.saveBindingIni(Module::BindingsIniPath)', 'loaded wheel profile is durable in canonical binding file')
req(bind_ui, 'wheel_profile_exists_cached', 'input profile overwrite check uses cached list')
req(bind_ui, 'WheelProfileStore::profile_exists(WheelProfileStore::Kind::Input, requestedName)', 'input profile rechecks overwrite on save click')
req(wheel_ui, 'ffb_profile_exists_cached', 'FFB profile overwrite check uses cached list')
req(wheel_ui, 'WheelProfileStore::profile_exists(WheelProfileStore::Kind::ForceFeedback, requested)', 'FFB profile rechecks overwrite on save click')
req(input_hpp, 'file.flush();', 'binding/profile writer checks buffered write errors')
req(wheel_ui, 'Force Feedback Profiles', 'FFB UI exposes named profiles')
req(wheel_ui, 'WheelProfileStore::save_ffb_profile', 'FFB UI saves named profile')
req(wheel_ui, 'WheelProfileStore::load_ffb_profile', 'FFB UI loads named profile')
req(wheel_ui, 'WheelFFB_RequestSettingsTransition();', 'profile/preset switching requests safe FFB transition')
req(wheel_ui, 'WheelFFBDamperStrength.ptr(), 0.0f, 1.0f', 'Dynamic Damping UI exposes full supported range')
req(ffb, 'void settings_transition()', 'FFB engine has profile transition safety path')
req(ffb, 'updateCounter_ = 59;', 'profile transition recreates newly enabled hardware effects promptly')
req(ffb, 'settings/profile transition; forces zeroed, periodic model reset and warm-up restarted', 'profile transition is observable in logs')
req(ffb, 'void WheelFFB_RequestSettingsTransition()', 'FFB settings transition exported to UI')
req(dyn, 'rawFrontSlip_', 'raw front-slip telemetry retained')
req(dyn, 'frontSlipBlend_ = 0.24f + (0.58f - 0.24f) * transientT;', 'front-slip transient accelerates with speed')
req(dyn, 'bodySlipBlend_ = 0.18f + (0.34f - 0.18f) * transientT;', 'body-slip transient accelerates with speed')
req(dyn, 'yawRateBlend_ = 0.20f + (0.38f - 0.20f) * transientT;', 'yaw transient accelerates with speed')
req(math, 'lateral_force_shape(float alpha)', 'front lateral-force proxy curve')
req(math, 'pneumatic_trail_factor(float alpha)', 'pneumatic trail separated')
req(math, 'mechanical_sat_shape(float forceAlpha, float mechanicalTrailRatio)', 'mechanical trail is an explicit lateral-force term')
req(math, 'float forceAlpha, float trailAlpha, float mechanicalTrailRatio', 'combined SAT separates force and trail transients')
forbid(math, 'mix * fy * (1.0f - pneumatic)', 'mechanical trail is never gated as a pneumatic fallback')
req(ffb, 'WheelFFBMechanicalTrail', 'mechanical trail setting')
req(ffb, 'WheelFFBTrailResponseLead', 'pneumatic trail phase-lead setting')
req(ffb, 'trailResponseSlip = std::clamp(', 'pneumatic trail uses bounded phase-led slip')
req(ffb, 'WheelFFBMath::pneumatic_sat_shape(frontSlip, trailResponseSlip)', 'lateral force remains filtered while trail response can lead')
req(ffb, 'trailResponseSlip={} trailResponseLead={}', 'phase-lead state is visible in telemetry')
req(wheel_ui, 'Pneumatic Trail Response Lead', 'phase-lead tuning is reachable in FFB UI')
req(ffb, 'WheelFFB SATMODEL', 'raw/filtered and decomposed SAT telemetry')
req(runtime, 'WheelFFBHeadroomSnapshot', 'shared headroom snapshot API')
req(ffb, 'record_headroom(std::abs(total), headroomEligible);', 'structural headroom analyzer')
req(ffb, 'headroomSamples_ >= 600', 'gain recommendation waits for enough driving')
req(wheel_ui, 'FFB Headroom / Clipping', 'headroom UI exposed')
req(ffb, 'const bool headroomEligible =\n                modernStructural &&', 'headroom learning is limited to Modern/Hybrid structural models')
req(wheel_ui, 'Headroom recommendation is unavailable for condition-driven Original modes.', 'F11 does not suggest strength from incomplete Original-mode torque data')
req(wheel_ui, 'hardware condition torque is not plotted.', 'F11 graph explains missing Original-mode condition torque')
req(wheel_ui, 'Suggested Overall Strength', 'headroom gain recommendation exposed')
req(wheel_ui, 'ffbDirty_ = true;\n                    WheelFFB_ResetHeadroomStats();', 'live FFB edits reset stale headroom statistics')
req(wheel_ui, 'Physics / Structural', 'FFB UI groups structural physics')
req(wheel_ui, 'Steering Feel', 'FFB UI groups steering feel')
req(wheel_ui, 'Effects', 'FFB UI groups tactile effects')
req(wheel_ui, 'Mechanical / Caster Trail', 'mechanical trail tuning exposed')
req(ffb, 'WheelFFBResponseCorrection', 'optional response correction setting')
req(ffb, 'WheelFFBResponseLUT', 'per-wheel response LUT setting')
req(math, 'parse_response_lut', 'response LUT validation')
req(math, 'apply_response_lut', 'response LUT application')
req(ffb, 'apply_response_correction(levelBeforeResponse)', 'response correction is final ConstantForce mapping')
req(profiles, 'FFBResponseCorrection = ', 'wheel profile stores response correction enable')
req(profiles, 'FFBResponseLUT = ', 'wheel profile stores response LUT')
req(profiles, 'FFBMaxTorqueNm = ', 'wheel profile stores physical max torque')
req(profiles, 'key != "ResponseCorrection" && key != "ResponseLUT"', 'FFB feel profiles exclude hardware response curve')
req(profiles, 'key != "MaxTorqueNm"', 'FFB feel profiles exclude physical torque rating')
req(wheel_ui, 'Leave correction off for a linear DD wheel unless measured.', 'response correction UI defaults to measurement-first guidance')
req(ini, 'MechanicalTrail = 0.25', 'shipped mechanical trail default')
req(ini, 'TrailResponseLead = 0.25', 'shipped pneumatic trail phase-lead default')
req(ini, 'ResponseCorrection = false', 'shipped response correction disabled')
req(ini, 'MaxTorqueNm = 0.0', 'shipped wheel max torque unknown')
forbid(ffb, 'trying first attached non-virtual FFB device', 'no unrelated device fallback')
req(ffb, 'DIPROP_FFGAIN', 'device gain configured separately from effect gain')
forbid(ffb, 'apply_live_effect_gain', 'dead live effect-gain updater removed')
forbid(ffb, 'configured_effect_gain', 'effect gain fixed nominal at creation')
forbid(ffb, 'lastEffectGain_', 'dead live-gain state removed')
req(ffb, 'WheelFFB SAMPLE', '10Hz telemetry output')
forbid(dyn, 'sampleValid_ = calibrated_', 'stopped vehicle has no valid dynamic SAT sample')
req(dyn, 'headingValid_ = false; // The next heading', 'missing samples break derivative baseline')
req(ffb, 'const float physicsFallback = naturalSatTorque;', 'full Natural SAT fallback until Physics SAT is ready')
forbid(ffb, 'const float physicsFallback = vehicleDynamics_.calibrated()', 'no calibration-tick SAT hole')
req(math, 'inline float soft_saturate(float value)', 'linear-preserving C1 force limiter')
req(ffb, 'WheelFFBMath::soft_saturate(total)', 'production force path uses soft-knee limiter')
forbid(ffb, 'std::tanh(total)', 'ordinary SAT is not compressed by tanh')
req(ffb, 'bool steerSampleValid_ = false;', 'steering derivative has explicit baseline state')
req(ffb, 'smoothedSteerRate_ += (rawSteerRate - smoothedSteerRate_) * 0.45f;', 'steering-rate quantization filter')
req(ffb, 'steerRateRaw={} steerRateFiltered={}', 'raw and filtered steering-rate telemetry')
req(ffb, 'damperRequested={} damperRelease={} damperCoefficient={}', 'damper release visible in telemetry')
req(ffb, 'const LONG releaseMaxSlew = std::min(', 'stale torque has a dedicated faster release rate')
req(ffb, 'const bool oppositeTorqueDirection =', 'torque sign reversal is detected explicitly')
req(ffb, 'if (std::abs(prevStructuralLevel_) <= reversalReleaseMaxSlew)\n                    structuralLevel = 0;', 'sign reversal unloads old torque to zero before rebuilding')
req(ffb, 'unloadingStructural ? releaseMaxSlew : maxSlew', 'same-sign force unload remains faster than force build')
forbid(ffb, 'naturalSatTorque * 0.15f', 'Physics mode never falls back to weak 15 percent steering')
req(ffb, 'vehicleDynamics_.calibrated() && vehicleDynamics_.sampleValid()', 'Physics SAT requires a current valid motion sample')
req(ffb, 'const float physicsMix = vehicleDynamics_.sampleValid()', 'invalid dynamics falls back to Natural SAT immediately')
req(dyn, 'void reset_dynamic()', 'dynamic reset preserves calibrated vehicle basis')
req(ffb, 'vehicleDynamics_.reset_dynamic();', 'engine transitions preserve dynamics calibration')
req(dyn, 'calibrationSamples_ >= CalibrationSamplesRequired * 4', 'ambiguous basis calibration retries with a fresh window')
forbid(ffb, 'bypassSlew', 'events never bypass sustained steering slew')
req(ffb, 'const LONG eventLevel = static_cast<LONG>', 'events have an independent immediate output path')
req(ffb, 'const float softwareSpringSign = Settings::WheelFFBInvertSpring', 'Reverse Spring also controls software fallback')
req(ffb, 'driver autocenter state could not be read; leaving it unchanged', 'unknown driver autocenter state is never mutated')
req(ffb, 'smoothedLongAccel_ +=', 'weight-transfer acceleration is filtered')
req(ffb, 'std::clamp(configuredWeightTransfer, 0.0f, 1.5f)', 'weight-transfer setting is finite and bounded')
req(ffb, 'const LONG vibrationHeadroom =', 'software vibration cannot clip steering torque')
req(ffb, 'const LONG levelBeforeResponse = baseSteeringLevel + vibrationLevel;', 'fallback vibration uses only remaining output headroom before wheel response correction')
req(ffb, 'periodicsActive_ && (updateCounter_ % 2) == 0', 'hardware periodic envelopes update at about 30 Hz')
dynamic_reset_start = dyn.find('void reset_dynamic()')
dynamic_reset_end = dyn.find('void update(', dynamic_reset_start)
if not (0 <= dynamic_reset_start < dynamic_reset_end):
    raise SystemExit('CURRENT VERIFY FAILED [dynamic reset section]')
dynamic_reset = dyn[dynamic_reset_start:dynamic_reset_end]
req(dynamic_reset, 'motionScaleEma_ = 0.0f;', 'dynamic reset clears old motion-scale EMA')
req(dynamic_reset, 'motionScaleSamples_ = 0;', 'dynamic reset clears old motion-scale sample count')
req(ffb, 'if (!car)\n            {\n                if (initialized_)\n                {\n                    zero_all_forces();', 'null car immediately clears active DD torque')
req(ffb, '? (vehicleDynamics_.sampleValid() ? "ACTIVE" : "FALLBACK")', 'diagnostics report Natural fallback instead of stale Physics hold')
forbid(ffb, '? (vehicleDynamics_.sampleValid() ? "ACTIVE" : "HOLD")', 'diagnostics never claim invalid Physics SAT is held')
req(wheel_ui, 'FFB selection and tuning apply live', 'F11 footer matches live FFB reinitialization')
forbid(wheel_ui, 'Restart after switching to a different physical wheel', 'new-input FFB page has no stale restart requirement')
forbid(wheel_ui, 'Restart after switching physical devices', 'legacy FFB page has no stale restart requirement')
forbid(ffb, 'if (!initialized_ && gameHwnd_ && GetForegroundWindow() == gameHwnd_)', 'foreground recovery is not gated on initialization state')
req(ffb, 'if (gameHwnd_ && GetForegroundWindow() == gameHwnd_)', 'foreground state can recover a missed activation message')
req(ffb, 'update_spring(0.0f);\n                if (springEffect_)\n                    springEffect_->Stop();', 'live spring disable rechecks effect after zero update')
req(ffb, 'update_damper(0.0f);\n                if (damperEffect_)\n                    damperEffect_->Stop();', 'live damper disable rechecks effect after zero update')
forbid(ffb, 'DWORD recreateHoldoffUntil_', 'critical ConstantForce recovery has no shared periodic holdoff')
req(ffb, 'DWORD constantRecreateHoldoffUntil_ = 0;', 'ConstantForce recreation has an independent holdoff')
req(ffb, 'DWORD periodicRecreateHoldoffUntil_ = 0;', 'periodic recreation has an independent holdoff')
req(ffb, 'tick_before(now, constantRecreateHoldoffUntil_)', 'ConstantForce retries use the steering-specific holdoff')
req(ffb, 'tick_reached(GetTickCount(), periodicRecreateHoldoffUntil_)', 'periodic retries use the periodic-specific holdoff')
req(ffb, 'constantEffectPolar_ = polar;\n                prevConstantLevel_ = 0;\n                lastConstantWriteTick_ = 0;', 'validated ConstantForce descriptor resets accepted-output cache')
req(bind_ui, 'Press Up on the wheel D-pad/POV, or another menu button.', 'Quick Setup captures menu Up')
req(bind_ui, 'Press Right on the wheel D-pad/POV, or another menu button.', 'Quick Setup captures menu Right')
req(bind_ui, 'Press Down on the wheel D-pad/POV, or another menu button.', 'Quick Setup captures menu Down')
req(bind_ui, 'Press Left on the wheel D-pad/POV, or another menu button.', 'Quick Setup captures menu Left')
req(bind_ui, 'same_source_family', 'Quick Setup preserves unrelated input source families')
forbid(bind_ui, 'return !existing.isKeyboard();', 'Quick Setup never erases every non-keyboard binding')
req(bind_ui, 'Skip this step', 'Quick Setup supports optional controls')
req(bind_ui, 'Keep & Fine-tune', 'Quick Setup can continue into manual calibration')
req(bind_ui, 'Save & Return to game', 'manual binding edits have an explicit persistence exit')
req(wheel_ui, 'Open Input Bindings', 'Force Feedback page links directly to input setup')
req(wheel_ui, 'Overlay::RequestBindingDialog = true;', 'FFB input shortcut uses the modal request path')
req(wheel_ui, 'Advanced FFB tuning', 'dedicated FFB page exposes advanced supported tuning')
req(wheel_ui, 'Settings::WheelFFBSpringSaturation.ptr()', 'spring saturation is reachable from FFB UI')
req(wheel_ui, 'Settings::WheelFFBWeightTransfer.ptr()', 'weight transfer is reachable from FFB UI')
req(wheel_ui, 'Settings::WheelFFBSlewRate.ptr()', 'force slew is reachable from FFB UI')
readme = read('README.md')
wheel_doc = read('WHEEL_FFB.md')
req(readme, 'Load Universal Physics SAT', 'README names current universal Physics preset')
req(readme, 'Save & Return to game', 'README documents durable binding exit')
forbid(readme, 'MOZA R3 v0.1 (default)', 'README has no obsolete preset button')
forbid(readme, 'Refresh connected wheels', 'README has no obsolete refresh label')
req(wheel_doc, 'Advanced FFB tuning', 'architecture doc covers reachable advanced tuning')
forbid(wheel_doc, 'MOZA R3 v0.1 (default)', 'architecture doc has no obsolete preset button')
req(bind_ui, 'if (isListeningForInput == ListenState::False && !unsavedChanges)', 'Back/B cannot bypass unsaved binding persistence choice')
forbid(wheel_ui, '}\n\n            ImGui::SameLine();\n            ImGui::Checkbox("Diagnostic logging"', 'advanced FFB header does not share a line with diagnostics')
req(bind_ui, 'existingDevice->instanceId == candidateDevice->instanceId', 'Quick Setup replaces raw bindings only on the captured physical device')
forbid(bind_ui, 'if (candidate.isRawDevice()) return existing.isRawDevice();', 'Quick Setup never erases every raw-device binding family')
req(bind_ui, 'Discard edits & load?##load', 'loading cannot silently discard unsaved binding edits')
req(bind_ui, 'Could not save bindings. Check folder permissions', 'binding save failures are visible in the UI')
req(wheel_ui, 'bool ffbDirty_ = false;', 'FFB page tracks unsaved live tuning')
req(wheel_ui, 'Save Force Feedback*', 'FFB save button marks unsaved tuning')
req(wheel_ui, 'Unsaved FFB changes are active now but will be lost after restart.', 'FFB page explains live versus persisted tuning')
req(wheel_ui, 'Loaded MOZA R3 Physics SAT for this session, but could not save user.ini.', 'Physics preset never falsely reports a failed save')
req(wheel_ui, 'Loaded MOZA R3 Natural SAT for this session, but could not save user.ini.', 'Natural preset never falsely reports a failed save')
req(read('src/input_manager.cpp'), 'Settings::WheelInputCompatibility.needs_restart();', 'legacy compatibility mode is explicitly restart-bound')
req(wheel_ui, 'constexpr std::string_view prefix = "WheelUniversal";', 'raw WheelUniversal settings are owned only by dedicated legacy setup')
req(read('src/hooks_input.cpp'), 'Settings::WheelMenuDirectionFilter.hidden(Settings::UseNewInput);', 'legacy menu filter is hidden from default modern controls')
req(read('src/hooks_wheel_input_compat_v2.hpp'), 'Settings::WheelPedalSplitFix.hidden(Settings::UseNewInput);', 'legacy pedal workaround is hidden from default modern controls')
req(read('src/hooks_wheel_r3_menu_dpad.hpp'), 'Settings::WheelMenuR3DirectDPad.hidden(Settings::UseNewInput);', 'R3 legacy D-pad helper is hidden from default modern controls')
req(read('src/hooks_wheel_r3_menu_ab.hpp'), 'Settings::WheelMenuR3DirectAB.hidden(Settings::UseNewInput);', 'R3 legacy A/B helper is hidden from default modern controls')
req(read('src/overlay/settings_ui.cpp'), 'matches_search("Input Bindings", search)', 'settings search can still surface Input Bindings')
req(read('src/overlay/overlay.cpp'), 'Wheel users: configure steering, pedals, buttons and menu controls in Input Bindings', 'first-run overlay explains wheel input ownership')
release_notes = read('RELEASE_NOTES_v0.1.md')
req(release_notes, 'Load Universal Physics SAT', 'release notes name the current universal Physics preset')
req(release_notes, 'Save Force Feedback', 'release notes explain FFB persistence')
req(readme, 'Engine Vibration', 'README documents optional engine vibration')
req(readme, 'OFF by default', 'README documents engine vibration default off')
req(release_notes, 'Engine Vibration', 'release notes document optional engine vibration')
req(release_notes, '기본 OFF', 'Korean release notes document engine vibration default off')
forbid(release_notes, 'MOZA R3 v0.1 (default)', 'release notes have no deleted preset button')
forbid(release_notes, 'Dynamic Damping** | **0.42', 'release notes have no obsolete damping table')
print('CURRENT WHEEL FFB STRUCTURE VERIFIED; run verify_wheel_ffb_math.py for numerical tests')


# Setup/FFB UX and compatibility review guards.
req(ffb, 'WheelFFBReversalReleaseRate', 'dedicated counter-steer stale-torque release rate')
req(ffb, 'GetEffectInfo(&info, effectGuid)', 'DirectInput effect dynamic capability query')
req(ffb, 'DIEP_TYPESPECIFICPARAMS', 'dynamic type-specific capability gate')
req(ffb, 'WheelFFBStatusSnapshot status_snapshot() const', 'runtime FFB status snapshot')
req(ffb, 'WheelFFBGraphSnapshot graph_snapshot() const', 'runtime rolling force graph')
req(ffb, 'record_graph_sample(', 'force pipeline graph recorder')
req(runtime, 'WheelFFB_GetStatusSnapshot', 'status API exported to UI')
req(runtime, 'WheelFFB_GetGraphSnapshot', 'graph API exported to UI')
req(wheel_ui, 'Ready to Drive', 'setup readiness summary')
req(wheel_ui, 'FFB Runtime Status', 'driver/effect status panel')
req(wheel_ui, 'recommended: steering device', 'VID/PID steering-to-FFB recommendation')
req(wheel_ui, 'Revert unsaved FFB', 'live FFB revert action')
req(wheel_ui, 'Recent FFB Pipeline', 'FFB rolling pipeline graph')
req(wheel_ui, 'Countersteer Release Rate', 'counter-steer release UI')
req(bind_ui, 'LISTENING...##addBinding', 'manual add-binding target highlight')
req(bind_ui, 'const bool listeningHere', 'manual rebind button target highlight')
req(bind_ui, 'binding_conflicts', 'duplicate-control conflict warning')
req(bind_ui, 'Guided axis calibration', 'Quick Setup integrated axis calibration')

req(ffb, 'result.powerOff = (state & DIGFFS_POWEROFF) != 0;', 'FFB status distinguishes explicit power-off state')
req(wheel_ui, 'ffbStatus.powerOff || ffbStatus.safetySwitchOff || ffbStatus.userSwitchOff', 'FFB UI warns only on explicit driver OFF states')
forbid(ffb, 'rejecting this FFB interface', 'ConstantForce capability metadata cannot falsely reject the only actuator path')
req(wheel_ui, 'if (persisted)\n                            capture_saved_ffb();', 'loaded FFB profile updates revert baseline after persistence')
req(wheel_ui, 'listeningHere ? "LISTENING..." : "Bind"', 'legacy manual binding also highlights current target')

# final-postfix-regression-guards
req(bind_ui, 'prepared.axisMinimum = prepared.axisRest;', 'fresh Quick Setup raw axes start uncalibrated')
req(bind_ui, 'const bool readyToSaveAndDrive = coreControlsPresent && guidedCalibrationReady;', 'Quick Setup gates Save & Drive on core controls and raw calibration')
req(bind_ui, 'WheelFFB_ResetDirectionTest();', 'loading a wheel profile invalidates the old direction test')
req(runtime, 'void WheelFFB_ResetDirectionTest();', 'direction-test reset API')
req(ffb, 'directionTested_ = false;\n                    request_device_reinitialize("configured wheel identity changed", S_OK);', 'external FFB device identity changes invalidate direction test')
req(wheel_ui, 'if (changedOutput)\n                    WheelFFB_ResetDirectionTest();', 'F11 FFB device selection invalidates direction test immediately')
req(wheel_ui, 'bool debugLog = true;', 'FFB revert baseline includes diagnostic logging')
req(wheel_ui, 'savedFfb_.telemetry = Settings::WheelFFBTelemetry;', 'FFB revert baseline includes telemetry')
req(wheel_ui, 'if (currentSaved)\n                            capture_saved_ffb();', 'saving a named FFB profile refreshes the revert baseline')
req(wheel_ui, 'return !known ? "unknown" : (dynamic ? "yes" : "no");', 'FFB capability UI distinguishes unknown from yes')
req(wheel_ui, 'pending(\"FFB device (starts in gameplay)\");', 'Ready checklist treats menu-time FFB runtime as pending, not failed')
forbid(wheel_ui, '#include <cstdint>\n#include <cstdio>\n#include <cstdint>', 'duplicate cstdint include')

# debug10-regression-guards
req(bind_ui, 'void arm_release_guard(const InputBinding& binding)', 'Quick Setup owns a raw-axis release guard independent of calibration span')
req(bind_ui, 'releaseGuardBinding->axisMinimum = -32768;', 'zero-span Quick Setup axis gets transient release range')
if bind_ui.count('arm_release_guard(*quickSetupCandidate);') != 2:
    raise SystemExit('CURRENT VERIFY FAILED [Quick Setup confirm/retry both arm the axis release guard]')
print('OK [Quick Setup confirm/retry both arm the axis release guard]')
forbid(bind_ui, 'releaseGuardBinding = *quickSetupCandidate;', 'Quick Setup never uses zero-span candidate directly as release guard')
req(profiles, 'commit_staged_profile(', 'named profile writes use staged replacement')
req(bind_ui, 'WheelProfileStore::staged_profile_path(*profilePath)', 'input profile is fully staged before overwrite')
req(bind_ui, 'WheelProfileStore::commit_staged_profile(stagedPath, *profilePath, &error)', 'input profile overwrite preserves previous file until staged write completes')
req(profiles, 'const auto staged = staged_profile_path(*path);', 'FFB profile is fully staged before overwrite')
req(profiles, 'Failed while closing staged FFB profile.', 'FFB profile close failures are reported')
req(profiles, 'Failed while closing wheel-specific input options.', 'input profile option close failures are reported')
req(wheel_ui, 'capture_saved_ffb();\n                status_ = "Saved to OutRun2006Tweaks.user.ini";', 'legacy full user.ini save refreshes FFB revert baseline')
req(wheel_ui, 'capture_saved_ffb();\n                    status_ = "Selected FFB output and saved its exact DirectInput GUID.', 'FFB output selection refreshes revert baseline after full user.ini persistence')
req(wheel_ui, 'WheelProfileStore::directory(WheelProfileStore::Kind::ForceFeedback).string()', 'FFB page shows the actual runtime profile folder')


# engine-vibration-v02-regression-guards
req(ffb, 'Setting<bool> WheelFFBEngineVibration', 'engine vibration has an independent live toggle')
req(math, 'EngineHapticEstimate estimate_engine_haptics(', 'engine RPM estimator is production math')
req(ffb, 'WheelFFBMath::estimate_engine_haptics(', 'FFB core consumes the common engine estimator')
req(ffb, 'enginePhase_, engineAmp * effectRampScale, engineFreq', 'engine haptic uses ConstantForce fallback layer')
req(ffb, 'smoothedEngineRpm_ = 0.0f;', 'engine haptic state resets on transitions/off')
forbid(ffb, 'else if (speedNorm < 0.03f && car->pedal_amount_34 > 0)', 'legacy low-speed-only engine rumble removed')
req(wheel_ui, 'Checkbox("Engine Vibration", Settings::WheelFFBEngineVibration.ptr())', 'F11 exposes engine vibration toggle')
req(wheel_ui, 'SliderFloat("Engine Vibration Strength", Settings::WheelFFBEngineIdle.ptr()', 'F11 exposes engine vibration strength')
forbid(wheel_ui, 'SliderFloat("Engine Idle"', 'old duplicate Engine Idle slider removed')
req(wheel_ui, 'WheelFFBRoadTexture.ptr(), 0.0f, 1.0f', 'Road Detail UI covers the 0.60 universal preset')


# v01-final-engine-haptic-guards
req(ffb, '"WheelFFB", "EngineVibration", false', 'engine vibration is opt-in by default')
req(ffb, '"WheelFFB", "EngineIdle", 0.20f', 'engine vibration default strength is 0.20')
req(ffb, 'engineStrength * 0.22f * amplitudeScale * outputStrength', 'engine strength is internally kept subtle')
req(ffb, 'smoothedEngineAmp_', 'engine vibration amplitude is smoothed')
req(ffb, 'smoothedEngineFreq_', 'engine vibration frequency is smoothed')
req(ffb, 'engineReserve = std::clamp(', 'engine haptic gets a small continuity reserve')
req(wheel_ui, 'Engine Vibration Strength', 'engine vibration strength remains user-adjustable')
req(ini, 'EngineVibration = false', 'shipped engine vibration stays disabled')
req(ini, 'EngineIdle = 0.20', 'shipped optional engine strength is 0.20')


# v01-snow-latch-route-fork-regression-guards
req(build, 'const bool mixedTouchesSnowBaseline =', 'snow curb latch starts only from a transition touching the snow baseline')
req(build, 'result.surfaceMask[i] = car->water_flag_24C[i];', 'historical water_flag array is sampled as four per-wheel surface masks')
req(build, 'DWORD wheelWaterFlag = 0;', 'water classification is captured independently for each wheel')
req(build, 'result.waterWheelMask |= (1u << i);', 'stage-specific water wheels are retained in the road profile')
req(build, 'const bool mixedSurface = rawMixedSurface && nonWaterRough;', 'ordinary route forks and water do not trigger curb tactile boost')
req(build, 'const bool tactileSurface = nonWaterRough || snowCurbHeld;', 'curb compatibility path requires non-water roughness or an active snow latch')
req(build, 'surface.nonWaterMaximum - 0.30f', 'curb compatibility amplitude is based on non-water roughness')
req(build, 'waterOnlyRough', 'stage water is explicitly separated from curb compatibility')
req(build, '"WheelFFB STAGE:', 'stage identity is emitted into FFB diagnostics')
req(build, 'masks={:08X}/{:08X}/{:08X}/{:08X}', 'four raw surface masks are emitted into road diagnostics')
stage_map = read('docs/reverse/C2C_STAGE_FFB_MAP.md')
req(stage_map, 'Metropolis / reverse (11 / 41)', 'stage map retains verified mask-2 water mapping')
req(stage_map, 'Casino Town / reverse (18 / 48)', 'stage map retains verified mask-400000 mapping')
req(stage_map, 'Water is not promoted into the fixed curb-strength/SAT-unload path.', 'stage map documents water ownership boundary')
if build.count('snowCurbHoldUntil = now + SnowCurbHoldMs;') != 1:
    raise SystemExit('CURRENT VERIFY FAILED [snow curb hold deadline is re-armed outside confirmed mixed snow contact]')
print('OK [snow curb hold deadline has one confirmed-contact re-arm site]')
forbid(build, 'Extend while all tyres remain on the identified curb/shoulder.', 'uniform curb contact cannot indefinitely refresh snow latch')

# selectable-original-model regression guards
req(ffb, 'Setting<int> WheelFFBModel{', 'selectable FFB model setting exists')
req(ffb, '"WheelFFB", "Model", 0', 'Modern DD remains the shipped FFB model default')
req(math, 'enum class Model : int', 'production math defines stable FFB model IDs')
req(math, 'Model::ArcadeOriginal', 'Arcade Original model ID retained')
req(math, 'Model::ArcadeHybrid', 'Arcade Hybrid model ID retained')
req(math, 'Model::PS2OriginalExperimental', 'PS2 experimental model ID retained')
req(math, 'float arcade_speed_strength(float speedNorm)', 'Lindbergh-derived stepped arcade strength is production math')
req(math, 'ArcadeRoadSinePeriodMs = 70.0f', 'Arcade road Sine preserves observed 70ms plugin period')
req(math, 'ArcadeGearSinePeriodMs = 240.0f', 'Arcade gear Sine preserves observed 240ms plugin period')
req(math, 'ArcadeGearSineAmplitude = 0.10f', 'Arcade gear Sine preserves observed 0.10 source amplitude')
req(math, 'int ArcadeGearEventFrames = 15', 'Arcade gear Sine has one approximately 240ms 60Hz event window')
req(math, 'ArcadeConstantEventLengthMs = 80.0f', 'Arcade directional ConstantForce preserves OutRun2Real FeedbackLength=80ms')
req(math, 'int ArcadeConstantEventFrames = 5', 'Arcade directional ConstantForce maps to nearest 60Hz frame count')
req(math, 'float arcade_gear_sine_force(', 'Arcade gear Sine is production math')
req(math, 'CrashFallbackSpeedDropMin = 0.12f', 'shared emergency crash fallback ignores captured normal-deceleration cluster')
req(math, 'CrashFallbackSpeedDropFull = 0.36f', 'crash fallback severity uses captured large-impact upper bound')
req(math, 'bool crash_speed_drop_fallback(', 'crash fallback trigger is production math')
req(math, 'float crash_speed_drop_severity(', 'crash fallback severity is production math')
req(math, 'float frequency_hz_from_period_ms(float periodMs)', 'period-ms to DirectInput-Hz host translation is explicit')
req(math, 'float compose_arcade_directional_surface(', 'arcade surface transition composition is production math')
req(math, 'return transitionActive ? transitionForce : sustainedForce;', 'arcade transition replaces sustained directional surface force')
req(ffb, 'const bool arcadeEffects =', 'runtime explicitly gates arcade event semantics')
req(ffb, 'const float arcadeSpeedNorm = std::isfinite(speedRaw)', 'Arcade has a separate speed normalization with >1.0 headroom')
req(ffb, 'WheelFFBMath::arcade_speed_strength(arcadeSpeedNorm)', 'Arcade staircase does not consume Modern-clamped speedNorm')
forbid(ffb, 'WheelFFBMath::arcade_speed_strength(speedNorm)', 'Arcade 100 percent speed band cannot be made unreachable by Modern clamp')
req(ffb, 'update_gear_event(curGear, arcadeEffects, speedRaw);', 'Arcade gear trigger receives model and moving-speed context')
req(ffb, 'WheelFFBMath::arcade_gear_sine_force(', 'Arcade gear event uses recovered 240ms Sine waveform')
req(ffb, 'Settings::WheelFFBGearShift', 'Arcade gear event consumes live F11 host scaler')
req(ffb, 'const bool modernStructural =', 'runtime explicitly gates Modern DD SAT ownership')
req(ffb, 'WheelFFBMath::frequency_hz_from_period_ms(', 'arcade rough-surface Sine converts observed period to host frequency')
forbid(ffb, 'roadFreq = 70.0f;', 'Lindbergh 70ms period cannot regress to 70Hz')
req(ffb, 'arcadeSurfaceTransitionTimer_ = WheelFFBMath::ArcadeConstantEventFrames;', 'arcade rough-to-road transition uses reference ConstantForce lifetime')
req(ffb, 'arcadeSurfaceTransitionCode_ = 0x04;', 'arcade right-side transition code retained')
req(ffb, 'arcadeSurfaceTransitionCode_ = 0x14;', 'arcade opposite transition code retained')
req(ffb, 'WheelFFBMath::compose_arcade_directional_surface(', 'arcade transition owns directional surface output while active')
forbid(ffb, 'arcadeDirectionalSurface += arcadeSurfaceTransitionForce_;', 'arcade transition cannot cancel against opposite sustained surface force')
req(ffb, 'crashImpulseForce_ >= 0.0f ? 1.0f : -1.0f', 'arcade wall events preserve C2C-derived impact direction')
req(ffb, 'impactFrame < WheelFFBMath::ArcadeConstantEventFrames', 'arcade wall output uses reference 80ms lifetime')
req(ffb, 'const bool suppressStructuralForImpact =', 'structural crash suppression is model-aware')
req(ffb, 'impactAge < WheelFFBMath::ArcadeConstantEventFrames', 'Arcade structural suppression ends with its 80ms event')
req(ffb, 'ps2Original\n                        ? false', 'PS2 software condition fallback is not blanked by an unverified collision event')
forbid(ffb, 'if (crashImpulseTimer_ <= CrashCooldownFrames)', 'shared debounce timer cannot globally blank structural torque')
# Modern DD legitimately keeps its own <6 rebound phase; Arcade is guarded by
# the explicit ArcadeConstantEventFrames requirement above.
req(ffb, 'const bool collisionEdge = collision && !wasCollision;', 'shared crash detector identifies explicit C2C collision edge')
req(ffb, 'WheelFFBMath::crash_speed_drop_fallback(speedDrop, speed)', 'shared crash detector uses tested emergency deceleration fallback')
req(ffb, 'WheelFFB: collision state edge', 'collision-state witness has distinct diagnostic')
req(ffb, 'WheelFFB: crash fallback speedDrop=', 'speed-drop fallback has distinct diagnostic')
forbid(ffb, 'speedDrop > 0.03f', 'normal deceleration cannot regress to old crash threshold')
req(ffb, 'modernStructural ? modernSelfAligningTorque : 0.0f', 'original modes do not silently retain inferred Modern SAT')
req(ffb, 'model={} spd={:.2f}', 'compact diagnostics identify the active FFB model')
req(ffb, 'model={} car={}', '10Hz telemetry identifies the active FFB model')
req(build, 'ffbModel == WheelFFBMath::Model::ModernDD', 'Modern DD tactile wrapper cannot pre-shape original modes')
wrapper_start = build.find('void __cdecl WheelFFB_UpdateAfterPhysics(EVWORK_CAR* car)')
wrapper_end = build.find('namespace\n{\n    class VibrationRoutingFix', wrapper_start)
wrapper_block = build[wrapper_start:wrapper_end]
forbid(wrapper_block, 'Settings::WheelFFBUsePeriodicEffects = false;', 'shared compatibility wrapper cannot disable model-owned hardware periodic effects')
req(wrapper_block, 'Do not rewrite WheelFFBUsePeriodicEffects here.', 'wrapper documents live model-aware periodic ownership')
req(wheel_ui, 'Arcade Original (Lindbergh-derived)', 'F11 exposes Arcade Original model')
req(wheel_ui, 'Arcade + Modern Hybrid', 'F11 exposes Arcade Hybrid model')
req(wheel_ui, 'PS2 Original topology (Experimental)', 'F11 exposes PS2 experimental model')
req(wheel_ui, '// Arcade Original\'s verified rough-surface path is periodic.', 'Arcade shortcut documents hardware periodic ownership')
req(wheel_ui, '// The retail PS2 binary has explicit periodic download/update', 'PS2 shortcut documents verified periodic ownership')
original_shortcut = wheel_ui[wheel_ui.find('if (ImGui::Button("Use Arcade Original"))'):wheel_ui.find('if (ImGui::Button("Use Arcade Hybrid"))')]
hybrid_shortcut = wheel_ui[wheel_ui.find('if (ImGui::Button("Use Arcade Hybrid"))'):wheel_ui.find('if (ImGui::Button("Use PS2 Original (Experimental)"))')]
ps2_shortcut_start = wheel_ui.find('if (ImGui::Button("Use PS2 Original (Experimental)"))')
ps2_shortcut_end = wheel_ui.find('if (!Settings::UseNewInput)', ps2_shortcut_start)
ps2_shortcut = wheel_ui[ps2_shortcut_start:ps2_shortcut_end]
for block, label in (
    (original_shortcut, 'Arcade Original shortcut'),
    (hybrid_shortcut, 'Arcade Hybrid shortcut'),
    (ps2_shortcut, 'PS2 Original shortcut'),
):
    req(block, 'Settings::WheelFFBUsePeriodicEffects = true;', label + ' enables hardware periodic path')
    forbid(block, 'Settings::WheelFFBUsePeriodicEffects = false;', label + ' never disables verified periodic path')
    if label != 'PS2 Original shortcut':
        req(block, 'Settings::WheelFFBGearShift = 1.0f;', label + ' restores observed Arcade gear Sine amplitude')
        req(block, 'Settings::WheelFFBRoadTexture = 1.0f;', label + ' restores one-to-one Arcade road/surface host scaling')
        req(block, 'Settings::WheelFFBWallImpact = 1.0f;', label + ' restores one-to-one Arcade wall host scaling')
req(original_shortcut, 'Settings::WheelFFBSpringStrength = 0.50f;', 'Arcade Original shortcut restores OutRun2Real 50% SpringStrength')
req(original_shortcut, 'Settings::WheelFFBSpringSaturation = 1.00f;', 'Arcade Original shortcut restores Springi 0.50 saturation behavior')
req(original_shortcut, 'Settings::WheelFFBDamperStrength = 0.0f;', 'Arcade Original shortcut restores OutRun2Real no-damper baseline')
req(original_shortcut, 'Settings::WheelFFBUseHardwareDamper = false;', 'Arcade Original shortcut does not leave stale hardware Damper active')
forbid(hybrid_shortcut, 'Settings::WheelFFBSpringStrength = 0.50f;', 'Arcade Hybrid does not inherit Original condition baseline')
req(ps2, 'speedRaw / 0.875f', 'PS2 retail drive factor recovered from SLPM')
req(ps2, 'RetailSpringSaturationBase = 15', 'PS2 retail spring saturation base')
req(ps2, 'RetailSpringSaturationSpan = 45', 'PS2 retail spring saturation speed span')
req(ps2, 'RetailSpringCoefficient = 200', 'PS2 retail spring coefficient')
req(ps2, 'RetailDamperSaturation = 255', 'PS2 retail damper saturation')
req(ps2, 'RetailConstantMagnitudeCap = 220', 'PS2 retail constant magnitude cap')
req(ps2, 'RetailPeriodicBasePeriod = 100', 'PS2 retail Triangle base period')
req(ps2, 'RetailPeriodicPeriodSpan = 60', 'PS2 retail Triangle period span')
req(ps2, 'RetailPeriodicMagnitudeScale = 50', 'PS2 retail Type-4 magnitude scale')
req(ps2, 'RetailPeriodicStartThreshold = 27', 'PS2 retail Type-4 start threshold')
req(ps2, 'float surface_speed_factor(float speedRaw)', 'PS2 periodic source preserves min(field_1C4,1) factor')
req(ps2, 'int periodic_magnitude_raw(', 'PS2 retail periodic magnitude chain is production math')
req(ps2, 'if (raw < RetailPeriodicStartThreshold)', 'PS2 periodic raw magnitude below 27 is suppressed')
req(ps2, 'float retail_wheel_level_scale(int level)', 'PS2 retail 0..10 wheel feedback-level scaler is production math')
req(ps2, 'RetailSurfaceBoost = 1.25f', 'PS2 retail surface producer boost is preserved')
req(ps2, 'RetailSurfaceEnvelopeMax =', 'PS2 periodic source allows recovered envelope above one')
req(ps2, 'float surface_envelope(', 'PS2 retail surface-envelope shaping is production math')
req(ps2, 'carField268 < 0.10f', 'PS2 first recovered surface boost predicate')
req(ps2, 'carField264 > -0.10f', 'PS2 second recovered surface boost predicate')
req(ps2, 'return static_cast<float>(level + 1) / 11.0f;', 'PS2 retail wheel feedback level uses recovered (level+1)/11 multiplier')
forbid(ps2, 'activationScale', 'PS2 wheel-level multiplier is not mislabeled as activation ramp')
req(ps2, 'float wheelLevelScale = 1.0f', 'PS2 periodic helper names recovered wheel-level semantics')
req(ffb, '#include "wheel_ffb_ps2.hpp"', 'runtime consumes retail PS2 translation')
req(ffb, 'WheelFFBPS2::drive_factor(speedRaw)', 'PS2 runtime uses retail speed factor instead of Modern speedNorm')
road_section_start = ffb.find('float roadAmp =')
ps2_road_start = ffb.find('if (ps2Original)', road_section_start)
ps2_road_end = ffb.find('// Lindbergh-derived arcade reconstruction:', ps2_road_start)
ps2_road_block = ffb[ps2_road_start:ps2_road_end]
req(ps2_road_block, 'WheelFFBPS2::periodic_magnitude_raw(', 'PS2 road periodic uses recovered retail magnitude chain')
req(ps2_road_block, 'ps2RoadRaw < WheelFFBPS2::RetailPeriodicStartThreshold', 'PS2 road periodic applies recovered raw start threshold before host scaling')
req(ps2_road_block, 'WheelFFBPS2::surface_envelope(', 'PS2 road periodic applies recovered vehicle-state surface boost')
req(ps2_road_block, 'roughness, car->field_264, car->field_268', 'PS2 road surface boost consumes the recovered car-field predicates')
req(ps2_road_block, 'ps2SurfaceEnvelope, speedRaw, ps2DriveFactor', 'PS2 road periodic consumes boosted envelope plus both retail speed factors')
req(ffb, 'int ps2RoadRaw = 0;', 'PS2 raw retail magnitude is retained for telemetry')
req(ffb, 'surfaceRough={} ps2Surface={} ps2RoadRaw={} ps2Drive={} arcadeSpeedNorm={} arcadeSpeedStrength={}', '10Hz telemetry exposes PS2 road intermediates and Arcade speed-step input/output')
req(ffb, 'roughness, ps2SurfaceEnvelope, ps2RoadRaw, ps2DriveFactor,', 'PS2 telemetry arguments preserve retail road-chain fields')
req(ffb, 'arcadeSpeedNorm, arcadeSpeedStrength, roadAmp, slipAmp', 'Arcade speed-step telemetry is wired to the sample line')
forbid(ps2_road_block, 'textureRoughness', 'PS2 road periodic does not reuse Modern DD baseline-removal shaping')
req(ffb, 'WheelFFBPS2::spring_coefficient_norm()', 'PS2 runtime uses recovered spring coefficient')
req(ffb, 'WheelFFBPS2::spring_saturation_norm(ps2DriveFactor)', 'PS2 runtime uses recovered dynamic spring saturation')
req(ffb, 'void update_spring(float strength, float saturationOverride = -1.0f)', 'Spring update accepts the PS2 retail saturation override')
update_spring_start = ffb.find('void update_spring(float strength, float saturationOverride = -1.0f)')
update_spring_end = ffb.find('bool create_damper_effect()', update_spring_start)
update_spring_block = ffb[update_spring_start:update_spring_end]
req(update_spring_block, 'saturationOverride >= 0.0f', 'PS2 Spring saturation override is consumed only by the live update path')
create_spring_start = ffb.find('bool create_spring_effect()')
create_spring_end = ffb.find('void update_spring(', create_spring_start)
create_spring_block = ffb[create_spring_start:create_spring_end]
forbid(create_spring_block, 'saturationOverride', 'create-time Spring code cannot reference the update-only override')
req(ffb, 'WheelFFBPS2::damper_coefficient_norm(ps2DriveFactor)', 'PS2 runtime uses recovered speed-fading damper coefficient')
ps2_event_start = ffb.find('else if (ps2Original)')
ps2_event_end = ffb.find('else\n                    {', ps2_event_start)
ps2_event_block = ffb[ps2_event_start:ps2_event_end]
req(ps2_event_block, 'no verified non-zero retail ConstantForce caller', 'PS2 collision path documents the missing retail non-zero caller')
req(ps2_event_block, 'event output suppressed', 'PS2 C2C collision is diagnostic-only until retail evidence exists')
forbid(ps2_event_block, 'result +=', 'PS2 Original does not synthesize an unverified C2C collision ConstantForce')
forbid(ps2_event_block, 'translatedSeverity', 'removed provisional PS2 collision magnitude translation cannot return')
req(ffb, ': (!ps2Original &&\n                   crashImpulseTimer_ > CrashCooldownFrames);', 'PS2 original spring is not suppressed by an unverified Modern collision interaction')
forbid(ffb, 'crashImpulseForce_ * 0.45f', 'arbitrary PS2 collision multiplier removed')
forbid(ffb, '(ps2Original ? 0.12f : 0.20f)', 'unsupported PS2 gear thunk removed')
req(ffb, 'else if (!ps2Original)', 'PS2 original mode emits no unverified generic gear-shift thunk')
req(wheel_ui, 'PS2 Original: gear-shift FFB stays disabled until a retail PS2 effect caller is verified.', 'F11 marks PS2 gear effect unavailable pending retail evidence')
req(wheel_ui, 'Arcade: Road Detail / Collision / Gear Shift at 1.00 preserve reconstructed source amplitude', 'F11 documents Arcade host-scaler semantics')
req(wheel_ui, 'const bool modelUsesCollisionEvent = activeFfbModel != 3;', 'F11 disables Collision control in PS2 Original')
req(wheel_ui, 'collision ConstantForce stays disabled until a non-zero retail event caller is verified.', 'F11 explains why PS2 Collision is disabled')
req(ffb, 'GUID_Triangle', 'PS2 retail Type 4 is translated to DirectInput Triangle')
req(ps2, 'float triangle_wave(float phaseCycles)', 'PS2 software fallback uses an explicit Triangle waveform')
req(ffb, 'synth_ps2_triangle_fallback(', 'PS2 Triangle remains Triangle when hardware periodic is unavailable')
req(ffb, 'WheelFFBPS2::triangle_wave(cycles) * amplitude', 'PS2 software Triangle uses the common tested waveform')
req(ffb, 'int activeRuntimeModel_ = -1;', 'runtime tracks periodic ownership by complete FFB model')
req(ffb, 'if (activeRuntimeModel_ != runtimeModelValue)', 'every live FFB model change rebuilds model-owned periodic objects')
req(ffb, 'live force-model change {} -> {}; recreating model-owned periodic set', 'runtime model self-heal is observable')
req(ffb, 'roadPeriodicIsTriangle_ != ps2Original', 'periodic creator still rejects an already-live wrong road waveform')
req(ffb, 'if (roadTextureEffect_ || tireSlipEffect_)\n                disable_periodics();', 'explicit settings/model transitions destroy waveform-bound periodic objects')
req(ffb, 'const bool needSlip =\n                WheelFFBMath::model_uses_modern_sat(model);', 'periodic set requires tire slip only for Modern/Hybrid')
req(ffb, '(!needSlip || tireSlipEffect_ != nullptr)', 'Original modes do not require unused Modern tyre-slip periodic')
req(ffb, 'roadPeriodicStrategy_', 'road periodic owns independent driver update strategy')
req(ffb, 'bool roadPeriodicCapsKnown_ = false;', 'road periodic keeps independent capability state')
req(ffb, 'bool slipPeriodicCapsKnown_ = false;', 'tire periodic keeps independent capability state')
req(ffb, 'roadPeriodicDynamicParams_', 'road periodic dynamic capability is retained for F11 diagnostics')
req(ffb, 'slipPeriodicDynamicParams_', 'tire periodic dynamic capability is retained for F11 diagnostics')
req(ffb, 'const bool statusNeedsSlip =', 'periodic runtime status is model-aware')
forbid(ffb, 'periodicCapsKnown_', 'removed shared periodic capability state cannot return')
forbid(ffb, 'periodicDynamicParams_', 'removed shared periodic dynamic state cannot return')
req(ffb, 'slipPeriodicStrategy_', 'tire periodic owns independent driver update strategy')
req(ffb, 'roadPeriodicIsTriangle_\n                            ? "GUID_Triangle road periodic"', 'safety zero path preserves road waveform identity')
forbid(ffb, 'update_periodic(roadTextureEffect_, roadState_, 0.0f, 30.0f);', 'no stale four-argument road periodic safety call')
forbid(ffb, 'update_periodic(tireSlipEffect_, slipState_, 0.0f, 35.0f);', 'no stale four-argument tire periodic safety call')
forbid(ffb, 'int periodicStrategy_ =', 'shared periodic strategy removed')
req(wheel_ui, 'Hardware road/slip periodic effects', 'F11 periodic control is waveform-neutral')
req(wheel_ui, 'modelUsesModernTireSlip', 'F11 disables ignored tire-slip tuning in original modes')
req(wheel_ui, 'modelUsesEngineHaptics', 'F11 disables ignored engine haptic tuning outside Modern DD')
req(wheel_ui, 'if (!modelUsesModernSat) ImGui::BeginDisabled();\n                track_ffb_change(ImGui::SliderFloat("Weight Transfer"', 'F11 disables ignored Modern weight-transfer tuning in Original modes')
req(wheel_ui, 'if (modelUsesModernSat && Settings::WheelFFBPhysicsSat)', 'advanced pneumatic trail tuning requires active Modern SAT ownership')
req(wheel_ui, 'WheelFFBSpringSaturation = 0.775f;', 'PS2 shortcut restores 1x retail spring saturation scaler')
req(wheel_ui, 'WheelFFBDamperStrength = 0.30f;', 'PS2 shortcut restores 1x retail damper scaler')
req(ps2_shortcut, 'Settings::WheelFFBRoadTexture = 1.0f;', 'PS2 shortcut restores one-to-one retail road-detail scaler')
req(wheel_ui, 'savedFfb_.model = Settings::WheelFFBModel;', 'FFB revert snapshot includes model selection')
req(wheel_ui, 'Settings::WheelFFBModel = savedFfb_.model;', 'FFB revert restores model selection')
req(ini, 'Model = 0', 'shipped INI defaults to Modern DD')
model_doc = read('docs/reverse/FFB_MODEL_MODES.md')
req(model_doc, 'Why Xbox is not a selectable wheel model', 'Xbox rumble is explicitly excluded as a wheel model')
req(model_doc, 'Arcade Original (Lindbergh-derived)', 'model evidence document covers arcade reconstruction')
req(model_doc, 'PS2 Original topology (Experimental)', 'model evidence document covers PS2 evidence boundary')
forbid(ffb, 'XboxOriginal', 'Xbox rumble is not promoted into a selectable wheel model')

# v0.3 hardware compatibility regression guards
req(profiles, 'std::filesystem::copy_file(', 'named profile save has rename-to-copy fallback for Windows driver/filter edge cases')
req(profiles, 'Profile installation could not be verified.', 'named profile save verifies the final file exists')
req(wheel_ui, 'Direction test (not run)', 'direction-test checklist distinguishes pending from failure')
req(wheel_ui, 'Waiting / released / inactive is normal outside gameplay.', 'runtime status explains menu-time idle state')
req(wheel_ui, 'FFB profile save failed:', 'profile persistence failures are explicit')
req(wheel_ui, 'spdlog::error("{}", status_);', 'profile persistence failure is logged for remote testers')

# first-save profile regression guards
req(profiles, 'ec == std::errc::no_such_file_or_directory', 'missing profile is a normal first-save state')
req(profiles, 'inspect_regular_file(finalPath, finalExists, "the existing profile")', 'final profile existence check uses missing-safe helper')
req(profiles, 'inspect_regular_file(backup, backupExists, "the profile backup")', 'backup existence check uses missing-safe helper')
forbid(profiles, 'if (!finalExists && std::filesystem::is_regular_file(backup, ec) && !ec)', 'backup probe no longer treats missing backup as filesystem failure')
